/**
 * Seed parent universes, merge fragmented franchises, link unlinked items.
 * Run: npx tsx prisma/seed-universes.ts
 */
import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const DB_URL = "postgresql://postgres:Baylorlawsucks2021@db.shlyuoeabdaifketvaeo.supabase.co:5432/postgres";
const adapter = new PrismaPg({ connectionString: DB_URL });
const prisma = new PrismaClient({ adapter });

// ── Stats tracking ──
let parentUniversesCreated = 0;
let subFranchisesLinked = 0;
let itemsLinked = 0;
let franchisesMerged = 0;
let itemsCreatedFromApi = 0;
const notFound: string[] = [];

// ── Helper: find items by title pattern ──
async function findItems(patterns: string[], type?: string): Promise<{ id: number; title: string; type: string }[]> {
  const results: { id: number; title: string; type: string }[] = [];
  for (const pattern of patterns) {
    const items = await prisma.item.findMany({
      where: {
        title: { contains: pattern, mode: "insensitive" },
        ...(type ? { type } : {}),
        parentItemId: null,
        isUpcoming: false,
      },
      select: { id: true, title: true, type: true },
    });
    for (const item of items) {
      if (!results.find(r => r.id === item.id)) {
        results.push(item);
      }
    }
  }
  return results;
}

// ── Helper: find or create franchise ──
async function findOrCreateFranchise(
  name: string,
  icon: string = "🔗",
  parentId?: number | null
): Promise<number> {
  // Try to find existing
  const existing = await prisma.franchise.findFirst({
    where: { name: { equals: name, mode: "insensitive" } },
  });
  if (existing) {
    // Update parent if not set
    if (parentId && !existing.parentFranchiseId) {
      await prisma.franchise.update({
        where: { id: existing.id },
        data: { parentFranchiseId: parentId },
      });
      subFranchisesLinked++;
      console.log(`  Linked "${name}" → parent (id=${parentId})`);
    }
    return existing.id;
  }

  const created = await prisma.franchise.create({
    data: {
      name,
      icon,
      autoGenerated: false,
      confidenceTier: 0,
      parentFranchiseId: parentId || null,
    },
  });
  if (parentId) subFranchisesLinked++;
  console.log(`  Created franchise "${name}" (id=${created.id})`);
  return created.id;
}

// ── Helper: link items to franchise ──
async function linkItems(franchiseId: number, itemIds: number[]): Promise<number> {
  let linked = 0;
  for (const itemId of itemIds) {
    try {
      await prisma.franchiseItem.upsert({
        where: { franchiseId_itemId: { franchiseId, itemId } },
        update: {},
        create: { franchiseId, itemId, addedBy: "universe_seed" },
      });
      linked++;
    } catch {
      // Item already linked or doesn't exist
    }
  }
  itemsLinked += linked;
  return linked;
}

// ── Helper: merge franchise B into franchise A (move all items) ──
async function mergeFranchise(keepId: number, mergeId: number, keepName: string): Promise<void> {
  if (keepId === mergeId) return;
  // Move all items from mergeId to keepId
  const items = await prisma.franchiseItem.findMany({ where: { franchiseId: mergeId } });
  for (const item of items) {
    await prisma.franchiseItem.upsert({
      where: { franchiseId_itemId: { franchiseId: keepId, itemId: item.itemId } },
      update: {},
      create: { franchiseId: keepId, itemId: item.itemId, addedBy: "merge" },
    });
  }
  // Move child franchises
  await prisma.franchise.updateMany({
    where: { parentFranchiseId: mergeId },
    data: { parentFranchiseId: keepId },
  });
  // Delete old franchise items and franchise
  await prisma.franchiseItem.deleteMany({ where: { franchiseId: mergeId } });
  await prisma.franchise.delete({ where: { id: mergeId } }).catch(() => {});
  franchisesMerged++;
  console.log(`  Merged franchise ${mergeId} into ${keepId} (${keepName})`);
}

// ── Helper: search Google Books and create item ──
async function searchAndCreateBook(title: string, author: string): Promise<number | null> {
  try {
    const query = encodeURIComponent(`intitle:${title} inauthor:${author}`);
    const res = await fetch(`https://www.googleapis.com/books/v1/volumes?q=${query}&maxResults=3`);
    if (!res.ok) return null;
    const data = await res.json();
    if (!data.items || data.items.length === 0) {
      notFound.push(`${title} by ${author}`);
      return null;
    }

    // Find best match
    const best = data.items.find((v: any) => {
      const t = v.volumeInfo?.title?.toLowerCase() || "";
      const authors = (v.volumeInfo?.authors || []).map((a: string) => a.toLowerCase());
      return t.includes(title.toLowerCase().split(":")[0].toLowerCase()) &&
             authors.some((a: string) => a.includes(author.toLowerCase().split(" ").pop()!));
    }) || data.items[0];

    const vol = best.volumeInfo;
    if (!vol) return null;

    // Check if already exists
    const existing = await prisma.item.findFirst({
      where: {
        title: { contains: title.split(":")[0], mode: "insensitive" },
        type: "book",
      },
    });
    if (existing) return existing.id;

    // Create item
    const item = await prisma.item.create({
      data: {
        title: vol.title + (vol.subtitle ? `: ${vol.subtitle}` : ""),
        type: "book",
        year: parseInt(vol.publishedDate?.substring(0, 4) || "0"),
        description: vol.description || "",
        cover: vol.imageLinks?.thumbnail?.replace("http://", "https://") || "",
        genre: vol.categories || [],
        vibes: [],
        people: vol.authors?.map((a: string) => ({ name: a, role: "Author" })) || [],
        platforms: [],
        awards: [],
        ext: {},
        totalEp: vol.pageCount || 0,
      },
    });
    itemsCreatedFromApi++;
    console.log(`  Created book: "${item.title}" (id=${item.id})`);
    return item.id;
  } catch (e) {
    notFound.push(`${title} by ${author}`);
    return null;
  }
}

// ── Helper: delay to respect API limits ──
const delay = (ms: number) => new Promise(r => setTimeout(r, ms));

// ══════════════════════════════════════════════════════════════════════
// MAIN: Seed all universes
// ══════════════════════════════════════════════════════════════════════
async function main() {
  console.log("=== SEEDING PARENT UNIVERSES ===\n");

  // ── 1. MERGE FRAGMENTED FRANCHISES ──
  console.log("── Step 1: Merging fragmented franchises ──");

  // Merge Naruto fragments
  const narutoMain = await prisma.franchise.findFirst({ where: { name: "Naruto" } });
  const narutoShip = await prisma.franchise.findFirst({ where: { name: "Naruto Shippuden" } });
  const narutoMovie = await prisma.franchise.findFirst({ where: { name: { contains: "Naruto Shippuden the Movie" } } });
  if (narutoMain && narutoShip) await mergeFranchise(narutoMain.id, narutoShip.id, "Naruto");
  if (narutoMain && narutoMovie) await mergeFranchise(narutoMain.id, narutoMovie.id, "Naruto");

  // Merge Dragon Ball fragments
  const dbMain = await prisma.franchise.findFirst({ where: { name: "Dragon Ball" } });
  const dbz = await prisma.franchise.findFirst({ where: { name: "Dragon Ball Z" } });
  const dbzKai = await prisma.franchise.findFirst({ where: { name: "Dragon Ball Z Kai" } });
  const dbSuper = await prisma.franchise.findFirst({ where: { name: "Dragon Ball Super" } });
  if (dbMain && dbz) await mergeFranchise(dbMain.id, dbz.id, "Dragon Ball");
  if (dbMain && dbzKai) await mergeFranchise(dbMain.id, dbzKai.id, "Dragon Ball");
  if (dbMain && dbSuper) await mergeFranchise(dbMain.id, dbSuper.id, "Dragon Ball");

  // Merge Bleach fragments
  const bleachMain = await prisma.franchise.findFirst({ where: { name: "Bleach" } });
  const bleachMovie = await prisma.franchise.findFirst({ where: { name: { contains: "Bleach the Movie" } } });
  if (bleachMain && bleachMovie) await mergeFranchise(bleachMain.id, bleachMovie.id, "Bleach");

  // Merge BioShock fragments
  const bioMain = await prisma.franchise.findFirst({ where: { name: "BioShock" } });
  const bioInf = await prisma.franchise.findFirst({ where: { name: "BioShock Infinite" } });
  if (bioMain && bioInf) await mergeFranchise(bioMain.id, bioInf.id, "BioShock");

  // Merge Assassin's Creed fragments
  const acMain = await prisma.franchise.findFirst({ where: { name: "Assassin's Creed" } });
  const acValh = await prisma.franchise.findFirst({ where: { name: { contains: "Assassin's Creed Valhalla" } } });
  if (acMain && acValh) await mergeFranchise(acMain.id, acValh.id, "Assassin's Creed");

  // Merge Ghost in the Shell fragments
  const gitsMain = await prisma.franchise.findFirst({ where: { name: "Ghost in the Shell" } });
  const gits2 = await prisma.franchise.findFirst({ where: { name: { contains: "Ghost in the Shell 2" } } });
  if (gitsMain && gits2) await mergeFranchise(gitsMain.id, gits2.id, "Ghost in the Shell");

  // Merge "universe" duplicates into main franchises
  const dupePatterns = [
    ["My Hero Academia", "My Hero Academia universe"],
    ["Demon Slayer: Kimetsu no Yaiba", "Demon Slayer: Kimetsu no Yaiba universe"],
    ["Neon Genesis Evangelion", "Neon Genesis Evangelion universe"],
    ["The Last of Us", "The Last of Us universe"],
    ["Uncharted", "Uncharted universe"],
    ["Undertale", "Undertale universe"],
    ["Metal Gear Solid", "Metal Gear universe"],
    ["Persona", "Persona universe"],
    ["Baldur's Gate", "Baldur's Gate III"],
    ["Breaking Bad", "Gilliverse"],
    ["Elder Scrolls", "The Elder Scrolls Online"],
    ["Pokémon", "Pokémon X"],
    ["Halo", "Halo Wars"],
    ["Super Mario", "Super Mario Advance"],
    ["Super Mario", "Super Mario Galaxy"],
    ["Jurassic Park", "Jurassic World"],
    ["Metroid", "Metroid Prime"],
  ];

  for (const [mainName, dupeName] of dupePatterns) {
    const main = await prisma.franchise.findFirst({ where: { name: { contains: mainName, mode: "insensitive" } }, orderBy: { id: "asc" } });
    const dupe = await prisma.franchise.findFirst({ where: { name: { equals: dupeName, mode: "insensitive" } } });
    if (main && dupe && main.id !== dupe.id) {
      await mergeFranchise(main.id, dupe.id, mainName);
    }
  }

  // Merge Mob Psycho
  const mob = await prisma.franchise.findFirst({ where: { name: { contains: "Mob Psycho" } }, orderBy: { id: "asc" } });
  if (mob) {
    const mob2 = await prisma.franchise.findFirst({ where: { name: { contains: "Mob Psycho" }, NOT: { id: mob.id } } });
    if (mob2) await mergeFranchise(mob.id, mob2.id, "Mob Psycho 100");
  }

  // ── 2. SEED PARENT UNIVERSES ──
  console.log("\n── Step 2: Creating/linking parent universes ──");

  // === THE COSMERE ===
  console.log("\n📚 The Cosmere");
  const cosmereId = await findOrCreateFranchise("The Cosmere", "📚");
  parentUniversesCreated++;

  // Stormlight Archive
  const stormlightId = await findOrCreateFranchise("The Stormlight Archive", "⚔", cosmereId);
  const stormlightBooks = [
    "The Way of Kings", "Words of Radiance", "Oathbringer", "Rhythm of War", "Wind and Truth"
  ];
  for (const title of stormlightBooks) {
    let items = await findItems([title], "book");
    if (items.length === 0) {
      const id = await searchAndCreateBook(title, "Brandon Sanderson");
      if (id) items = [{ id, title, type: "book" }];
      await delay(300);
    }
    if (items.length > 0) await linkItems(stormlightId, items.map(i => i.id));
  }
  await linkItems(cosmereId, (await prisma.franchiseItem.findMany({ where: { franchiseId: stormlightId } })).map(fi => fi.itemId));

  // Mistborn Era 1
  const mistborn1Id = await findOrCreateFranchise("Mistborn Era 1", "🌫", cosmereId);
  for (const title of ["The Final Empire", "The Well of Ascension", "The Hero of Ages"]) {
    let items = await findItems([title], "book");
    if (items.length === 0) { const id = await searchAndCreateBook(title, "Brandon Sanderson"); if (id) items = [{ id, title, type: "book" }]; await delay(300); }
    if (items.length > 0) await linkItems(mistborn1Id, items.map(i => i.id));
  }

  // Mistborn Era 2
  const mistborn2Id = await findOrCreateFranchise("Mistborn Era 2", "🌫", cosmereId);
  for (const title of ["The Alloy of Law", "Shadows of Self", "The Bands of Mourning", "The Lost Metal"]) {
    let items = await findItems([title], "book");
    if (items.length === 0) { const id = await searchAndCreateBook(title, "Brandon Sanderson"); if (id) items = [{ id, title, type: "book" }]; await delay(300); }
    if (items.length > 0) await linkItems(mistborn2Id, items.map(i => i.id));
  }

  // Merge existing "Mistborn" franchise into Cosmere
  const mistbornOld = await prisma.franchise.findFirst({ where: { name: "Mistborn", NOT: { id: { in: [mistborn1Id, mistborn2Id] } } } });
  if (mistbornOld) {
    // Move items to era 1 or era 2 based on title
    const oldItems = await prisma.franchiseItem.findMany({ where: { franchiseId: mistbornOld.id }, include: { item: { select: { title: true, id: true } } } });
    for (const fi of oldItems) {
      const era2Titles = ["alloy", "shadows of self", "bands of mourning", "lost metal"];
      const isEra2 = era2Titles.some(t => fi.item.title.toLowerCase().includes(t));
      await linkItems(isEra2 ? mistborn2Id : mistborn1Id, [fi.itemId]);
      await linkItems(cosmereId, [fi.itemId]);
    }
    await prisma.franchiseItem.deleteMany({ where: { franchiseId: mistbornOld.id } });
    await prisma.franchise.delete({ where: { id: mistbornOld.id } }).catch(() => {});
  }

  // Standalone Cosmere
  for (const title of ["Warbreaker", "Elantris", "Tress of the Emerald Sea", "Yumi and the Nightmare Painter", "The Sunlit Man", "The Emperor's Soul"]) {
    let items = await findItems([title], "book");
    if (items.length === 0) { const id = await searchAndCreateBook(title, "Brandon Sanderson"); if (id) items = [{ id, title, type: "book" }]; await delay(300); }
    if (items.length > 0) await linkItems(cosmereId, items.map(i => i.id));
  }

  // Link all Cosmere sub-franchise items to parent
  for (const subId of [stormlightId, mistborn1Id, mistborn2Id]) {
    const subItems = await prisma.franchiseItem.findMany({ where: { franchiseId: subId } });
    await linkItems(cosmereId, subItems.map(fi => fi.itemId));
  }

  // === MIDDLE-EARTH ===
  console.log("\n💍 Middle-earth");
  const meId = await findOrCreateFranchise("Middle-earth", "💍");
  const existingME = await prisma.franchise.findFirst({ where: { name: "Middle-earth" } });
  if (existingME && existingME.id !== meId) await mergeFranchise(meId, existingME.id, "Middle-earth");
  parentUniversesCreated++;

  // LOTR sub-franchise
  const lotrId = await findOrCreateFranchise("The Lord of the Rings", "💍", meId);
  const existingLOTR = await prisma.franchise.findFirst({ where: { name: "The Lord of the Rings" } });
  if (existingLOTR && existingLOTR.id !== lotrId) {
    // It already has items, just set parent
    await prisma.franchise.update({ where: { id: existingLOTR.id }, data: { parentFranchiseId: meId } });
    subFranchisesLinked++;
  }

  // Hobbit sub-franchise
  const hobbitExisting = await prisma.franchise.findFirst({ where: { name: { contains: "Hobbit" } } });
  if (hobbitExisting) {
    await prisma.franchise.update({ where: { id: hobbitExisting.id }, data: { parentFranchiseId: meId } });
    subFranchisesLinked++;
  }

  // Find and link Tolkien books
  for (const title of ["The Silmarillion", "Unfinished Tales", "The Children of Hurin", "Beren and Luthien", "The Fall of Gondolin"]) {
    let items = await findItems([title], "book");
    if (items.length === 0) { const id = await searchAndCreateBook(title, "J.R.R. Tolkien"); if (id) items = [{ id, title, type: "book" }]; await delay(300); }
    if (items.length > 0) await linkItems(meId, items.map(i => i.id));
  }

  // Find Middle-earth games
  const meGames = await findItems(["Middle-earth", "Lord of the Rings", "Shadow of Mordor", "Shadow of War", "LEGO Lord"], "game");
  if (meGames.length > 0) await linkItems(meId, meGames.map(i => i.id));

  // Link Rings of Power
  const rop = await findItems(["Rings of Power"]);
  if (rop.length > 0) await linkItems(meId, rop.map(i => i.id));

  // Link all LOTR/Hobbit items to parent
  for (const fName of ["The Lord of the Rings", "The Hobbit"]) {
    const f = await prisma.franchise.findFirst({ where: { name: { contains: fName } } });
    if (f) {
      const fItems = await prisma.franchiseItem.findMany({ where: { franchiseId: f.id } });
      await linkItems(meId, fItems.map(fi => fi.itemId));
    }
  }

  // === STEPHEN KING UNIVERSE ===
  console.log("\n👑 Stephen King Universe");
  const skId = await findOrCreateFranchise("Stephen King Universe", "👑");
  parentUniversesCreated++;

  // Dark Tower sub-franchise
  const dtId = await findOrCreateFranchise("The Dark Tower", "🗼", skId);
  const existingDT = await prisma.franchise.findFirst({ where: { name: "The Dark Tower" } });
  if (existingDT && existingDT.id !== dtId) {
    await prisma.franchise.update({ where: { id: existingDT.id }, data: { parentFranchiseId: skId } });
    subFranchisesLinked++;
  }

  for (const title of ["The Gunslinger", "The Drawing of the Three", "The Waste Lands", "Wizard and Glass", "Wolves of the Calla", "Song of Susannah", "The Dark Tower", "The Wind Through the Keyhole"]) {
    let items = await findItems([title], "book");
    if (items.length === 0) { const id = await searchAndCreateBook(title, "Stephen King"); if (id) items = [{ id, title, type: "book" }]; await delay(300); }
    if (items.length > 0) { await linkItems(dtId, items.map(i => i.id)); await linkItems(skId, items.map(i => i.id)); }
  }

  // Connected King works
  for (const title of ["IT", "The Stand", "Salem's Lot", "Insomnia", "11/22/63", "The Mist", "Needful Things"]) {
    const items = await findItems([title]);
    if (items.length > 0) await linkItems(skId, items.map(i => i.id));
  }

  // === NASUVERSE ===
  console.log("\n⚔ Nasuverse");
  const nasuId = await findOrCreateFranchise("Nasuverse", "⚔");
  parentUniversesCreated++;

  // Link Fate sub-franchises
  for (const name of ["Fate/stay night", "Fate/Zero", "Fate/Grand Order", "Kara no Kyoukai", "Tsukihime"]) {
    const f = await prisma.franchise.findFirst({ where: { name: { contains: name, mode: "insensitive" } } });
    if (f && !f.parentFranchiseId) {
      await prisma.franchise.update({ where: { id: f.id }, data: { parentFranchiseId: nasuId } });
      subFranchisesLinked++;
    }
  }

  // Find Fate items in DB
  const fateItems = await findItems(["Fate/", "Fate/stay", "Fate/Zero", "Fate/Grand", "Fate/Apocrypha", "Fate/Extra", "Garden of Sinners", "Kara no Kyoukai", "Tsukihime"]);
  if (fateItems.length > 0) await linkItems(nasuId, fateItems.map(i => i.id));

  // === RIORDANVERSE ===
  console.log("\n⚡ Riordanverse");
  const riordanId = await findOrCreateFranchise("Riordanverse", "⚡");
  parentUniversesCreated++;

  // Link existing children
  for (const name of ["Percy Jackson", "Heroes of Olympus", "The Kane Chronicles", "Magnus Chase", "Trials of Apollo"]) {
    const f = await prisma.franchise.findFirst({ where: { name: { contains: name, mode: "insensitive" } } });
    if (f && !f.parentFranchiseId) {
      await prisma.franchise.update({ where: { id: f.id }, data: { parentFranchiseId: riordanId } });
      subFranchisesLinked++;
    }
    // Link all sub items to parent
    if (f) {
      const fItems = await prisma.franchiseItem.findMany({ where: { franchiseId: f.id } });
      await linkItems(riordanId, fItems.map(fi => fi.itemId));
    }
  }

  // Search for Percy Jackson movie/show
  const pjItems = await findItems(["Percy Jackson"]);
  if (pjItems.length > 0) await linkItems(riordanId, pjItems.map(i => i.id));

  // === DISCWORLD ===
  console.log("\n🐢 Discworld");
  const discId = await findOrCreateFranchise("Discworld", "🐢");
  parentUniversesCreated++;

  // Link existing children
  for (const name of ["City Watch", "Witches", "Death", "Rincewind", "Moist von Lipwig", "Tiffany Aching"]) {
    const f = await prisma.franchise.findFirst({ where: { name: { contains: name, mode: "insensitive" } } });
    if (f && !f.parentFranchiseId) {
      await prisma.franchise.update({ where: { id: f.id }, data: { parentFranchiseId: discId } });
      subFranchisesLinked++;
    }
    if (f) {
      const fItems = await prisma.franchiseItem.findMany({ where: { franchiseId: f.id } });
      await linkItems(discId, fItems.map(fi => fi.itemId));
    }
  }

  // Find Discworld items
  const discItems = await findItems(["Discworld", "Terry Pratchett"], "book");
  if (discItems.length > 0) await linkItems(discId, discItems.map(i => i.id));

  // Find TV adaptations
  const discTv = await findItems(["Going Postal", "Hogfather", "The Colour of Magic"]);
  for (const item of discTv) {
    await linkItems(discId, [item.id]);
  }

  // === WARHAMMER 40K ===
  console.log("\n🔨 Warhammer 40,000");
  const w40kId = await findOrCreateFranchise("Warhammer 40,000", "🔨");
  parentUniversesCreated++;

  const w40kItems = await findItems(["Warhammer", "Dawn of War", "Space Marine", "Darktide", "Mechanicus", "Boltgun", "Horus Heresy", "Eisenhorn", "Gaunt's Ghosts", "Ciaphas Cain"]);
  if (w40kItems.length > 0) await linkItems(w40kId, w40kItems.map(i => i.id));

  // === DRAGON AGE ===
  console.log("\n🐉 Dragon Age");
  const daId = await findOrCreateFranchise("Dragon Age", "🐉");
  parentUniversesCreated++;

  const daExisting = await prisma.franchise.findFirst({ where: { name: "Dragon Age" } });
  if (daExisting && daExisting.id !== daId) await mergeFranchise(daId, daExisting.id, "Dragon Age");

  const daItems = await findItems(["Dragon Age", "Dawn of the Seeker"], undefined);
  if (daItems.length > 0) await linkItems(daId, daItems.map(i => i.id));

  for (const title of ["The Stolen Throne", "The Calling", "Asunder", "The Masked Empire", "Last Flight"]) {
    let items = await findItems([title], "book");
    // Dragon Age books are generic titles — only link if by David Gaider or related
    if (items.length > 0) {
      const daBooks = items.filter(i => i.title.toLowerCase().includes("dragon age") || i.title.toLowerCase().includes(title.toLowerCase()));
      if (daBooks.length > 0) await linkItems(daId, daBooks.map(i => i.id));
    }
  }

  // === MASS EFFECT ===
  console.log("\n🚀 Mass Effect");
  const meEffId = await findOrCreateFranchise("Mass Effect", "🚀");
  parentUniversesCreated++;

  const meEffExisting = await prisma.franchise.findFirst({ where: { name: "Mass Effect" } });
  if (meEffExisting && meEffExisting.id !== meEffId) await mergeFranchise(meEffId, meEffExisting.id, "Mass Effect");

  const meEffItems = await findItems(["Mass Effect", "Paragon Lost"]);
  if (meEffItems.length > 0) await linkItems(meEffId, meEffItems.map(i => i.id));

  // === DUNE ===
  console.log("\n🏜 Dune");
  const duneId = await findOrCreateFranchise("Dune Universe", "🏜");
  parentUniversesCreated++;

  const duneExisting = await prisma.franchise.findFirst({ where: { name: "Dune" } });
  if (duneExisting) {
    await prisma.franchise.update({ where: { id: duneExisting.id }, data: { parentFranchiseId: duneId } });
    subFranchisesLinked++;
    const duneItems = await prisma.franchiseItem.findMany({ where: { franchiseId: duneExisting.id } });
    await linkItems(duneId, duneItems.map(fi => fi.itemId));
  }

  // Find more Dune books
  for (const title of ["Dune Messiah", "Children of Dune", "God Emperor of Dune", "Heretics of Dune", "Chapterhouse"]) {
    let items = await findItems([title], "book");
    if (items.length === 0) { const id = await searchAndCreateBook(title, "Frank Herbert"); if (id) items = [{ id, title, type: "book" }]; await delay(300); }
    if (items.length > 0) await linkItems(duneId, items.map(i => i.id));
  }

  // Find Dune games/movies/TV
  const duneMedia = await findItems(["Dune", "Spice Wars", "Dune Prophecy"]);
  if (duneMedia.length > 0) await linkItems(duneId, duneMedia.map(i => i.id));

  // === HALO ===
  console.log("\n🎯 Halo");
  const haloId = await findOrCreateFranchise("Halo", "🎯");
  parentUniversesCreated++;

  const haloExisting = await prisma.franchise.findFirst({ where: { name: "Halo" } });
  if (haloExisting && haloExisting.id !== haloId) await mergeFranchise(haloId, haloExisting.id, "Halo");

  const haloItems = await findItems(["Halo"]);
  if (haloItems.length > 0) await linkItems(haloId, haloItems.map(i => i.id));

  // Halo novels
  for (const title of ["The Fall of Reach", "The Flood", "First Strike", "Ghosts of Onyx", "Contact Harvest"]) {
    let items = await findItems([title], "book");
    if (items.length > 0) await linkItems(haloId, items.map(i => i.id));
  }

  // === THE WITCHER ===
  console.log("\n⚔ The Witcher");
  const witcherId = await findOrCreateFranchise("The Witcher", "⚔");
  parentUniversesCreated++;

  const witcherExisting = await prisma.franchise.findFirst({ where: { name: "The Witcher" } });
  if (witcherExisting && witcherExisting.id !== witcherId) await mergeFranchise(witcherId, witcherExisting.id, "The Witcher");

  // Search for Witcher books
  for (const title of ["The Last Wish", "Sword of Destiny", "Blood of Elves", "Time of Contempt", "Baptism of Fire", "The Tower of the Swallow", "The Lady of the Lake", "Season of Storms"]) {
    let items = await findItems([title], "book");
    if (items.length === 0) { const id = await searchAndCreateBook(title, "Andrzej Sapkowski"); if (id) items = [{ id, title, type: "book" }]; await delay(300); }
    if (items.length > 0) await linkItems(witcherId, items.map(i => i.id));
  }

  const witcherItems = await findItems(["Witcher", "Nightmare of the Wolf"]);
  if (witcherItems.length > 0) await linkItems(witcherId, witcherItems.map(i => i.id));

  // === DC UNIVERSE ===
  console.log("\n🦇 DC Universe");
  const dcId = await findOrCreateFranchise("DC", "🦇");
  parentUniversesCreated++;

  const dcExisting = await prisma.franchise.findFirst({ where: { name: "DC" } });
  if (dcExisting && dcExisting.id !== dcId) await mergeFranchise(dcId, dcExisting.id, "DC");

  // Link Batman as child
  const batman = await prisma.franchise.findFirst({ where: { name: "Batman" } });
  if (batman) {
    await prisma.franchise.update({ where: { id: batman.id }, data: { parentFranchiseId: dcId } });
    subFranchisesLinked++;
    const batItems = await prisma.franchiseItem.findMany({ where: { franchiseId: batman.id } });
    await linkItems(dcId, batItems.map(fi => fi.itemId));
  }

  // Create other DC sub-franchises
  for (const name of ["Superman", "Wonder Woman", "The Flash", "Aquaman", "Justice League"]) {
    const subId = await findOrCreateFranchise(name, "🦸", dcId);
    const items = await findItems([name]);
    if (items.length > 0) {
      await linkItems(subId, items.map(i => i.id));
      await linkItems(dcId, items.map(i => i.id));
    }
  }

  // Find Arkham/Injustice games
  const dcGames = await findItems(["Arkham", "Injustice", "Gotham Knights", "Suicide Squad"]);
  if (dcGames.length > 0) await linkItems(dcId, dcGames.map(i => i.id));

  // === MARVEL UNIVERSE ===
  console.log("\n🦸 Marvel Universe");
  const marvelId = await findOrCreateFranchise("Marvel", "🦸");
  parentUniversesCreated++;

  const marvelExisting = await prisma.franchise.findFirst({ where: { name: "Marvel" } });
  if (marvelExisting && marvelExisting.id !== marvelId) await mergeFranchise(marvelId, marvelExisting.id, "Marvel");

  // Link Spider-Man and X-Men as children
  const spiderman = await prisma.franchise.findFirst({ where: { name: "Spider-Man" } });
  if (spiderman) {
    await prisma.franchise.update({ where: { id: spiderman.id }, data: { parentFranchiseId: marvelId } });
    subFranchisesLinked++;
    const spItems = await prisma.franchiseItem.findMany({ where: { franchiseId: spiderman.id } });
    await linkItems(marvelId, spItems.map(fi => fi.itemId));
  }
  const xmen = await prisma.franchise.findFirst({ where: { name: "X-Men" } });
  if (xmen) {
    await prisma.franchise.update({ where: { id: xmen.id }, data: { parentFranchiseId: marvelId } });
    subFranchisesLinked++;
    const xmItems = await prisma.franchiseItem.findMany({ where: { franchiseId: xmen.id } });
    await linkItems(marvelId, xmItems.map(fi => fi.itemId));
  }

  // Merge MCU into Marvel
  const mcu = await prisma.franchise.findFirst({ where: { name: { contains: "Marvel Cinematic" } } });
  if (mcu) await mergeFranchise(marvelId, mcu.id, "Marvel");

  // Create sub-franchises
  for (const name of ["Avengers", "Iron Man", "Captain America", "Thor", "Guardians of the Galaxy", "Daredevil"]) {
    const subId = await findOrCreateFranchise(name, "🦸", marvelId);
    const items = await findItems([name]);
    if (items.length > 0) {
      await linkItems(subId, items.map(i => i.id));
      await linkItems(marvelId, items.map(i => i.id));
    }
  }

  // Marvel games
  const marvelGames = await findItems(["Marvel", "Spider-Man", "Wolverine", "Avengers"], "game");
  if (marvelGames.length > 0) await linkItems(marvelId, marvelGames.map(i => i.id));

  // === STAR WARS ===
  console.log("\n⭐ Star Wars");
  const swId = await findOrCreateFranchise("Star Wars", "⭐");
  parentUniversesCreated++;

  const swExisting = await prisma.franchise.findFirst({ where: { name: "Star Wars" } });
  if (swExisting && swExisting.id !== swId) await mergeFranchise(swId, swExisting.id, "Star Wars");

  const swItems = await findItems(["Star Wars", "Mandalorian", "Andor", "Ahsoka", "Obi-Wan", "Clone Wars", "Rebels", "Bad Batch", "Acolyte", "Rogue One", "KOTOR", "Jedi Fallen", "Jedi Survivor", "Battlefront", "Thrawn"]);
  if (swItems.length > 0) await linkItems(swId, swItems.map(i => i.id));

  // ── 3. FIND AND LINK UNLINKED ITEMS BY FRANCHISE NAME ──
  console.log("\n── Step 3: Linking unlinked items to existing franchises ──");

  const allFranchises = await prisma.franchise.findMany({
    include: { items: { select: { itemId: true } } },
  });

  for (const f of allFranchises) {
    if (f.name.length < 4) continue; // Skip very short names
    // Search for items matching franchise name
    const searchName = f.name
      .replace(/ universe$/i, "")
      .replace(/^The /i, "")
      .replace(/: .*$/, ""); // Get base name

    if (searchName.length < 4) continue;

    const matchingItems = await prisma.item.findMany({
      where: {
        title: { contains: searchName, mode: "insensitive" },
        parentItemId: null,
        isUpcoming: false,
      },
      select: { id: true, title: true },
    });

    const existingIds = new Set(f.items.map(fi => fi.itemId));
    const newItems = matchingItems.filter(i => !existingIds.has(i.id));

    if (newItems.length > 0 && newItems.length <= 20) {
      // Only auto-link if reasonable number (avoid noise)
      await linkItems(f.id, newItems.map(i => i.id));
      if (newItems.length > 0) {
        console.log(`  ${f.name}: linked ${newItems.length} new items`);
      }
    }
  }

  // ── REPORT ──
  console.log("\n══════════════════════════════════");
  console.log("=== SEEDING COMPLETE ===");
  console.log(`Parent universes created/ensured: ${parentUniversesCreated}`);
  console.log(`Sub-franchises linked to parents: ${subFranchisesLinked}`);
  console.log(`Items linked to franchises: ${itemsLinked}`);
  console.log(`Franchises merged (deduped): ${franchisesMerged}`);
  console.log(`Items created from Google Books: ${itemsCreatedFromApi}`);

  if (notFound.length > 0) {
    console.log(`\nItems NOT found in any API (${notFound.length}):`);
    for (const nf of notFound) console.log(`  - ${nf}`);
  }

  // Final count
  const finalFranchises = await prisma.franchise.count();
  const finalLinked = await prisma.$queryRaw<{ count: bigint }[]>`SELECT COUNT(DISTINCT item_id) as count FROM franchise_items`;
  const totalItems = await prisma.item.count({ where: { parentItemId: null, isUpcoming: false } });
  console.log(`\nFinal: ${finalFranchises} franchises, ${Number(finalLinked[0].count)}/${totalItems} items linked`);

  await prisma.$disconnect();
}

main().catch(e => { console.error(e); process.exit(1); });
