import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

/** GET /api/admin/franchises — List all franchises with their items */
export async function GET() {
  try {
    const franchises = await prisma.franchise.findMany({
      orderBy: { createdAt: "desc" },
      include: {
        items: {
          include: {
            item: {
              select: { id: true, title: true, type: true, year: true, cover: true },
            },
          },
        },
      },
    });

    return NextResponse.json(franchises);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

/** POST /api/admin/franchises — Create a new franchise manually */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { name, icon, description, itemIds } = body;

    if (!name || !itemIds || !Array.isArray(itemIds) || itemIds.length < 2) {
      return NextResponse.json({ error: "Name and at least 2 item IDs required" }, { status: 400 });
    }

    const franchise = await prisma.franchise.create({
      data: {
        name,
        icon: icon || "🔗",
        description: description || "",
        autoGenerated: false,
        confidenceTier: 0,
        items: {
          create: itemIds.map((id: number) => ({
            itemId: id,
            addedBy: "manual",
          })),
        },
      },
      include: {
        items: {
          include: {
            item: {
              select: { id: true, title: true, type: true, year: true, cover: true },
            },
          },
        },
      },
    });

    return NextResponse.json(franchise);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

/** DELETE /api/admin/franchises?id=X — Delete a franchise */
export async function DELETE(req: NextRequest) {
  const id = parseInt(req.nextUrl.searchParams.get("id") || "0");
  if (!id) return NextResponse.json({ error: "ID required" }, { status: 400 });

  try {
    await prisma.franchise.delete({ where: { id } });
    return NextResponse.json({ success: true });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
