import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { rateLimit } from "@/lib/validation";

/** GET /api/admin/suggestions — List all pending suggestions */
export async function GET(req: NextRequest) {
  const ip = req.headers.get("x-forwarded-for") || "unknown";
  if (!rateLimit(`admin-suggestions:${ip}`, 120, 60_000)) {
    return NextResponse.json({ error: "Too many requests. Please try again in a moment." }, { status: 429, headers: { "Retry-After": "60" } });
  }

  try {
    const suggestions = await prisma.suggestedConnection.findMany({
      where: { reviewed: false },
      orderBy: { confidenceTier: "asc" },
    });

    // Fetch item details for each suggestion
    const itemIds = new Set<number>();
    for (const s of suggestions) {
      itemIds.add(s.itemId1);
      itemIds.add(s.itemId2);
    }

    const items = await prisma.item.findMany({
      where: { id: { in: [...itemIds] } },
      select: { id: true, title: true, type: true, year: true, cover: true },
    });

    const itemMap = new Map(items.map((i) => [i.id, i]));

    const enriched = suggestions.map((s) => ({
      ...s,
      item1: itemMap.get(s.itemId1) || null,
      item2: itemMap.get(s.itemId2) || null,
    }));

    return NextResponse.json(enriched);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

/** POST /api/admin/suggestions — Approve or reject a suggestion */
export async function POST(req: NextRequest) {
  const ip = req.headers.get("x-forwarded-for") || "unknown";
  if (!rateLimit(`admin-suggestions-post:${ip}`, 120, 60_000)) {
    return NextResponse.json({ error: "Too many requests. Please try again in a moment." }, { status: 429, headers: { "Retry-After": "60" } });
  }

  try {
    const { id, action } = await req.json();

    if (!id || !["approve", "reject"].includes(action)) {
      return NextResponse.json({ error: "ID and action (approve/reject) required" }, { status: 400 });
    }

    const suggestion = await prisma.suggestedConnection.update({
      where: { id },
      data: {
        reviewed: true,
        approved: action === "approve",
      },
    });

    // If approved, create a franchise
    if (action === "approve" && suggestion.itemId1 !== suggestion.itemId2) {
      const items = await prisma.item.findMany({
        where: { id: { in: [suggestion.itemId1, suggestion.itemId2] } },
        select: { id: true, title: true },
      });

      if (items.length === 2) {
        await prisma.franchise.create({
          data: {
            name: items[0].title.replace(/[:–—]\s.*$/, "").trim(),
            icon: "✅",
            description: `Approved from suggestion: ${suggestion.reason}`,
            autoGenerated: false,
            confidenceTier: 3,
            items: {
              create: items.map((item) => ({
                itemId: item.id,
                addedBy: "manual",
              })),
            },
          },
        });
      }
    }

    return NextResponse.json({ success: true });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
