/**
 * Franchise Detection v2 — Comprehensive cross-media connection finder
 *
 * Methods (run in order):
 * 1. Wikidata — P144 (based on), P4969 (derivative), P179 (series), P1434 (universe)
 * 2. API-native — TMDB collections, Jikan relations, IGDB franchises
 * 3. Exact title matching across media types
 * 4. Manual seed for known edge cases
 *
 * Run: npx tsx scripts/detect-franchises-v2.ts
 */
import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const TMDB_KEY = process.env.TMDB_API_KEY!;
const IGDB_ID = process.env.IGDB_CLIENT_ID!;
const IGDB_SECRET = process.env.IGDB_CLIENT_SECRET!;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function fetchJson(url: string, opts?: RequestInit): Promise<any> {
  const res = await fetch(url, opts);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}

interface DbItem {
  id: number;
  title: string;
  type: string;
  year: number;
  people: any;
  cover: string;
  genre: string[];
}

const stats = {
  wikidata: 0,
  tmdb_collection: 0,
  jikan_relations: 0,
  igdb_franchise: 0,
  exact_title: 0,
  manual: 0,
  total_franchises: 0,
  total_items_linked: 0,
};

async function main() {
  console.log("🔍 Franchise Detection v2\n");

  const connUrl = process.env.DIRECT_URL || process.env.DATABASE_URL!;
  const adapter = new PrismaPg({ connectionString: connUrl });
  const prisma = new PrismaClient({ adapter });

  // Clear old franchise data for clean run
  await prisma.franchiseItem.deleteMany({});
  await prisma.franchise.deleteMany({});
  await prisma.suggestedConnection.deleteMany({});
  console.log("🗑  Cleared old franchise data\n");

  const items = await prisma.item.findMany({
    where: { isUpcoming: false },
    select: { id: true, title: true, type: true, year: true, people: true, cover: true, genre: true },
  });
  console.log(`📊 ${items.length} items loaded\n`);

  const alreadyLinked = new Set<number>();

  // Helper to create franchise and track
  async function createFranchise(name: string, icon: string, itemIds: number[], source: string) {
    const uniqueIds = [...new Set(itemIds)].filter((id) => !alreadyLinked.has(id));
    if (uniqueIds.length < 2) return null;

    try {
      const f = await prisma.franchise.create({
        data: {
          name,
          icon,
          description: `Auto-detected via ${source}`,
          cover: items.find((i) => uniqueIds.includes(i.id))?.cover || "",
          autoGenerated: true,
          confidenceTier: source === "wikidata" || source === "tmdb_collection" ? 1 : 2,
          items: {
            create: uniqueIds.map((id) => ({ itemId: id, addedBy: source })),
          },
        },
      });
      uniqueIds.forEach((id) => alreadyLinked.add(id));
      (stats as any)[source] = ((stats as any)[source] || 0) + 1;
      stats.total_franchises++;
      stats.total_items_linked += uniqueIds.length;
      return f;
    } catch (e: any) {
      if (!e.message?.includes("Unique constraint")) {
        console.warn(`  ⚠ Failed: ${e.message?.slice(0, 80)}`);
      }
      return null;
    }
  }

  // ══════════════════════════════════════════════════════════════════════
  // METHOD 1: WIKIDATA
  // ══════════════════════════════════════════════════════════════════════
  console.log("═══ METHOD 1: Wikidata Cross-Media Links ═══\n");

  // Properties to check: P144 (based on), P4969 (derivative work), P179 (part of series)
  const wikidataCache = new Map<string, string[]>(); // entityId -> related entity IDs
  const itemWikidataMap = new Map<number, string>(); // our item ID -> wikidata entity ID

  // Search Wikidata for each item type and find connections
  const typeLabels: Record<string, string> = {
    movie: "film", tv: "television series", book: "book", manga: "manga",
    game: "video game", music: "album", comic: "comic book series", podcast: "podcast",
  };

  // Process items in batches to find Wikidata entities
  const wikidataGroups = new Map<string, number[]>(); // wikidata series/universe ID -> item IDs

  // Sample the most popular items across types (processing all 1300+ would take too long)
  const sampleItems = items
    .filter((i) => ["movie", "tv", "book", "manga", "game", "comic"].includes(i.type))
    .slice(0, 300);

  for (let i = 0; i < sampleItems.length; i++) {
    const item = sampleItems[i];
    try {
      // Search for this item on Wikidata
      const searchUrl = `https://www.wikidata.org/w/api.php?action=wbsearchentities&search=${encodeURIComponent(item.title)}&language=en&type=item&limit=3&format=json`;
      const searchData = await fetchJson(searchUrl);
      await sleep(1100); // Respect rate limits

      const results = searchData.search || [];
      if (results.length === 0) continue;

      // Find the best match
      const exactMatch = results.find((r: any) =>
        r.label?.toLowerCase() === item.title.toLowerCase()
      ) || results[0];

      if (!exactMatch) continue;

      const entityId = exactMatch.id;
      itemWikidataMap.set(item.id, entityId);

      // Get entity details with claims
      const entityUrl = `https://www.wikidata.org/w/api.php?action=wbgetentities&ids=${entityId}&props=claims&format=json`;
      const entityData = await fetchJson(entityUrl);
      await sleep(1100);

      const entity = entityData.entities?.[entityId];
      if (!entity?.claims) continue;

      // Check P179 (part of the series)
      const seriesClaims = entity.claims.P179 || [];
      for (const claim of seriesClaims) {
        const seriesId = claim.mainsnak?.datavalue?.value?.id;
        if (seriesId) {
          if (!wikidataGroups.has(seriesId)) wikidataGroups.set(seriesId, []);
          wikidataGroups.get(seriesId)!.push(item.id);
        }
      }

      // Check P1434 (takes place in fictional universe)
      const universeClaims = entity.claims.P1434 || [];
      for (const claim of universeClaims) {
        const universeId = claim.mainsnak?.datavalue?.value?.id;
        if (universeId) {
          if (!wikidataGroups.has(universeId)) wikidataGroups.set(universeId, []);
          wikidataGroups.get(universeId)!.push(item.id);
        }
      }

      // Check P144 (based on) — link to source material
      const basedOnClaims = entity.claims.P144 || [];
      for (const claim of basedOnClaims) {
        const sourceId = claim.mainsnak?.datavalue?.value?.id;
        if (sourceId) {
          // Find if we have the source work in our DB
          const sourceEntityUrl = `https://www.wikidata.org/w/api.php?action=wbgetentities&ids=${sourceId}&props=labels&languages=en&format=json`;
          const sourceData = await fetchJson(sourceEntityUrl);
          await sleep(1100);

          const sourceLabel = sourceData.entities?.[sourceId]?.labels?.en?.value;
          if (sourceLabel) {
            const matchedSource = items.find((si) =>
              si.id !== item.id &&
              si.title.toLowerCase() === sourceLabel.toLowerCase()
            );
            if (matchedSource) {
              const key = `based-${[item.id, matchedSource.id].sort().join("-")}`;
              if (!wikidataGroups.has(key)) wikidataGroups.set(key, []);
              wikidataGroups.get(key)!.push(item.id);
              wikidataGroups.get(key)!.push(matchedSource.id);
            }
          }
        }
      }

      if (i % 20 === 0) {
        console.log(`  Processed ${i + 1}/${sampleItems.length}...`);
      }
    } catch (e: any) {
      // Skip individual failures
    }
  }

  // Create franchises from Wikidata groups
  for (const [groupId, itemIds] of wikidataGroups) {
    const uniqueIds = [...new Set(itemIds)].filter((id) => !alreadyLinked.has(id));
    if (uniqueIds.length < 2) continue;

    // Get group name from Wikidata
    let groupName = items.find((i) => uniqueIds.includes(i.id))?.title || "Unknown";
    try {
      if (groupId.startsWith("Q")) {
        const labelUrl = `https://www.wikidata.org/w/api.php?action=wbgetentities&ids=${groupId}&props=labels&languages=en&format=json`;
        const labelData = await fetchJson(labelUrl);
        await sleep(1100);
        const label = labelData.entities?.[groupId]?.labels?.en?.value;
        if (label) groupName = label;
      }
    } catch {}

    // Normalize name
    groupName = groupName.replace(/ series$/, "").replace(/ franchise$/, "").replace(/ universe$/, "");

    const f = await createFranchise(groupName, "🔗", uniqueIds, "wikidata");
    if (f) {
      const itemNames = uniqueIds.map((id) => items.find((i) => i.id === id)?.title).join(", ");
      console.log(`  ✓ "${groupName}" — ${uniqueIds.length} items: ${itemNames}`);
    }
  }

  console.log(`  Wikidata: ${stats.wikidata} franchises\n`);

  // ══════════════════════════════════════════════════════════════════════
  // METHOD 2: API-NATIVE GROUPINGS
  // ══════════════════════════════════════════════════════════════════════
  console.log("═══ METHOD 2: API-Native Groupings ═══\n");

  // TMDB Collections
  console.log("📽  TMDB Collections...");
  const movieItems = items.filter((i) => i.type === "movie" && !alreadyLinked.has(i.id));
  const collectionMap = new Map<string, { name: string; items: DbItem[] }>();

  for (const item of movieItems.slice(0, 200)) {
    try {
      const searchData = await fetchJson(
        `https://api.themoviedb.org/3/search/movie?api_key=${TMDB_KEY}&query=${encodeURIComponent(item.title)}&year=${item.year}`
      );
      const match = (searchData.results || []).find((r: any) =>
        r.title?.toLowerCase() === item.title.toLowerCase()
      );
      if (match) {
        const details = await fetchJson(
          `https://api.themoviedb.org/3/movie/${match.id}?api_key=${TMDB_KEY}`
        );
        if (details.belongs_to_collection) {
          const coll = details.belongs_to_collection;
          const key = `tmdb-${coll.id}`;
          if (!collectionMap.has(key)) collectionMap.set(key, { name: coll.name, items: [] });
          collectionMap.get(key)!.items.push(item);
        }
      }
      await sleep(260);
    } catch {}
  }

  for (const [, coll] of collectionMap) {
    const ids = coll.items.map((i) => i.id);
    const f = await createFranchise(
      coll.name.replace(" Collection", ""),
      "🎬",
      ids,
      "tmdb_collection"
    );
    if (f) console.log(`  ✓ "${coll.name.replace(" Collection", "")}" — ${ids.length} movies`);
  }

  // Jikan Relations (manga ↔ anime)
  console.log("\n🗾 Jikan Relations...");
  const mangaItems = items.filter((i) => i.type === "manga" && !alreadyLinked.has(i.id));
  const validRelations = new Set(["Adaptation", "Sequel", "Prequel", "Parent story", "Side story", "Spin-off"]);

  for (const manga of mangaItems.slice(0, 80)) {
    try {
      const searchData = await fetchJson(
        `https://api.jikan.moe/v4/manga?q=${encodeURIComponent(manga.title)}&limit=3`
      );
      await sleep(400);

      const match = (searchData.data || []).find((m: any) => {
        const jTitle = (m.title_english || m.title || "").toLowerCase();
        return jTitle === manga.title.toLowerCase();
      });
      if (!match) continue;

      const relData = await fetchJson(`https://api.jikan.moe/v4/manga/${match.mal_id}/relations`);
      await sleep(400);

      for (const rel of relData.data || []) {
        if (!validRelations.has(rel.relation)) continue;
        for (const entry of rel.entry || []) {
          if (entry.type !== "anime") continue;
          const eTitle = (entry.name || "").toLowerCase();
          const animeMatch = items.find((i) => {
            if (i.type !== "tv" || alreadyLinked.has(i.id)) return false;
            const iTitle = i.title.toLowerCase();
            return iTitle === eTitle || iTitle.replace(/[:–—]\s.*$/, "").trim() === eTitle.replace(/[:–—]\s.*$/, "").trim();
          });
          if (animeMatch) {
            const f = await createFranchise(manga.title, "🗾", [manga.id, animeMatch.id], "jikan_relations");
            if (f) console.log(`  ✓ "${manga.title}" — manga ↔ anime [${rel.relation}]`);
          }
        }
      }
    } catch {}
  }

  // IGDB Franchises
  console.log("\n🎮 IGDB Franchises...");
  let igdbToken = "";
  try {
    const tokenData = await fetchJson(
      `https://id.twitch.tv/oauth2/token?client_id=${IGDB_ID}&client_secret=${IGDB_SECRET}&grant_type=client_credentials`,
      { method: "POST" }
    );
    igdbToken = tokenData.access_token;
  } catch {}

  if (igdbToken) {
    const gameItems = items.filter((i) => i.type === "game" && !alreadyLinked.has(i.id));
    const igdbMap = new Map<number, { name: string; items: DbItem[] }>();

    const gameTitles = gameItems.slice(0, 100).map((g) => `"${g.title.replace(/"/g, '\\"')}"`).join(",");
    try {
      const res = await fetch("https://api.igdb.com/v4/games", {
        method: "POST",
        headers: { "Client-ID": IGDB_ID, Authorization: `Bearer ${igdbToken}`, "Content-Type": "text/plain" },
        body: `fields name,franchise.name,franchises.name; where name = (${gameTitles}) & franchise != null; limit 100;`,
      });
      const games = await res.json();

      for (const g of games) {
        const dbMatch = gameItems.find((i) => i.title.toLowerCase() === (g.name || "").toLowerCase());
        if (!dbMatch || !g.franchise?.id || !g.franchise?.name) continue;
        if (!igdbMap.has(g.franchise.id)) igdbMap.set(g.franchise.id, { name: g.franchise.name, items: [] });
        igdbMap.get(g.franchise.id)!.items.push(dbMatch);
      }
    } catch {}

    for (const [, fran] of igdbMap) {
      const ids = fran.items.map((i) => i.id);
      const f = await createFranchise(fran.name, "🎮", ids, "igdb_franchise");
      if (f) console.log(`  ✓ "${fran.name}" — ${ids.length} games`);
    }
  }

  // ══════════════════════════════════════════════════════════════════════
  // METHOD 3: EXACT TITLE MATCHING ACROSS TYPES
  // ══════════════════════════════════════════════════════════════════════
  console.log("\n═══ METHOD 3: Exact Title Matching ═══\n");

  function normalizeTitle(title: string): string {
    return title.toLowerCase().replace(/[:–—]\s.*$/, "").replace(/\s*\(.*?\)\s*/g, "").trim();
  }

  const titleGroups = new Map<string, DbItem[]>();
  for (const item of items) {
    if (alreadyLinked.has(item.id)) continue;
    const norm = normalizeTitle(item.title);
    if (!titleGroups.has(norm)) titleGroups.set(norm, []);
    titleGroups.get(norm)!.push(item);
  }

  for (const [normTitle, group] of titleGroups) {
    if (group.length < 2) continue;
    const types = new Set(group.map((i) => i.type));
    if (types.size < 2) continue; // Must span multiple media types

    const ids = group.map((i) => i.id);
    const f = await createFranchise(
      group[0].title.replace(/[:–—]\s.*$/, "").replace(/\s*\(.*?\)\s*/g, "").trim(),
      "🔗",
      ids,
      "exact_title"
    );
    if (f) {
      const itemDescs = group.map((i) => `${i.title} (${i.type})`).join(", ");
      console.log(`  ✓ "${normTitle}" — ${ids.length} items: ${itemDescs}`);
    }
  }

  // ══════════════════════════════════════════════════════════════════════
  // METHOD 4: MANUAL SEED for known edge cases
  // ══════════════════════════════════════════════════════════════════════
  console.log("\n═══ METHOD 4: Manual Seed ═══\n");

  const manualFranchises = [
    { name: "Blade Runner", icon: "🌃", titles: ["Do Androids Dream of Electric Sheep?", "Blade Runner", "Blade Runner 2049"] },
    { name: "Game of Thrones", icon: "👑", titles: ["A Game of Thrones", "Game of Thrones", "House of the Dragon"] },
    { name: "Cyberpunk", icon: "🌆", titles: ["Cyberpunk 2077", "Cyberpunk: Edgerunners"] },
    { name: "Cowboy Bebop", icon: "🚀", titles: ["Cowboy Bebop"] },
    { name: "The Lord of the Rings", icon: "💍", titles: ["The Lord of the Rings", "The Fellowship of the Ring", "The Two Towers", "The Return of the King", "The Rings of Power", "The Hobbit"] },
    { name: "Harry Potter", icon: "⚡", titles: ["Harry Potter"] },
    { name: "Star Wars", icon: "⭐", titles: ["Star Wars", "The Empire Strikes Back", "Return of the Jedi", "The Phantom Menace", "A New Hope", "The Force Awakens", "Rogue One", "The Mandalorian", "Andor"] },
    { name: "Marvel", icon: "🦸", titles: ["Avengers", "Spider-Man", "Iron Man", "Thor", "Captain America", "Black Panther", "Doctor Strange", "Guardians of the Galaxy", "Ant-Man", "Deadpool", "Wolverine", "X-Men"] },
    { name: "DC", icon: "🦇", titles: ["Batman", "Superman", "Wonder Woman", "The Flash", "Aquaman", "Justice League", "Joker"] },
    { name: "Pokémon", icon: "⚡", titles: ["Pokémon", "Pokemon"] },
    { name: "Dragon Ball", icon: "🐉", titles: ["Dragon Ball"] },
    { name: "Naruto", icon: "🍥", titles: ["Naruto"] },
    { name: "One Piece", icon: "🏴‍☠️", titles: ["One Piece"] },
    { name: "Zelda", icon: "🗡️", titles: ["Zelda", "The Legend of Zelda"] },
    { name: "Final Fantasy", icon: "⚔️", titles: ["Final Fantasy"] },
    { name: "Persona", icon: "🎭", titles: ["Persona"] },
    { name: "Resident Evil", icon: "🧟", titles: ["Resident Evil"] },
    { name: "The Witcher", icon: "⚔", titles: ["Witcher", "The Witcher"] },
    { name: "Dune", icon: "🏜", titles: ["Dune"] },
    { name: "Berserk", icon: "⚔", titles: ["Berserk"] },
    { name: "Fullmetal Alchemist", icon: "⚗️", titles: ["Fullmetal Alchemist"] },
    { name: "Death Note", icon: "📓", titles: ["Death Note"] },
    { name: "Attack on Titan", icon: "⚔", titles: ["Attack on Titan", "Shingeki no Kyojin"] },
    { name: "My Hero Academia", icon: "💪", titles: ["My Hero Academia", "Boku no Hero Academia"] },
    { name: "Demon Slayer", icon: "🗡️", titles: ["Demon Slayer", "Kimetsu no Yaiba"] },
    { name: "Jujutsu Kaisen", icon: "👁️", titles: ["Jujutsu Kaisen"] },
    { name: "Spy × Family", icon: "🕵️", titles: ["Spy x Family", "SPY×FAMILY", "Spy × Family"] },
    { name: "Chainsaw Man", icon: "🔪", titles: ["Chainsaw Man"] },
    { name: "Neon Genesis Evangelion", icon: "🤖", titles: ["Neon Genesis Evangelion", "Evangelion"] },
    { name: "Ghost in the Shell", icon: "🤖", titles: ["Ghost in the Shell"] },
    { name: "Halo", icon: "🎮", titles: ["Halo"] },
    { name: "The Last of Us", icon: "🍄", titles: ["The Last of Us"] },
  ];

  for (const mf of manualFranchises) {
    const matchedIds: number[] = [];
    for (const item of items) {
      if (alreadyLinked.has(item.id)) continue;
      const itemTitle = item.title.toLowerCase();
      for (const searchTitle of mf.titles) {
        if (itemTitle === searchTitle.toLowerCase() ||
            itemTitle.startsWith(searchTitle.toLowerCase() + ":") ||
            itemTitle.startsWith(searchTitle.toLowerCase() + " ")) {
          matchedIds.push(item.id);
          break;
        }
      }
    }

    if (matchedIds.length >= 2) {
      const f = await createFranchise(mf.name, mf.icon, matchedIds, "manual");
      if (f) {
        const itemDescs = matchedIds.slice(0, 5).map((id) => items.find((i) => i.id === id)?.title).join(", ");
        console.log(`  ✓ "${mf.name}" — ${matchedIds.length} items: ${itemDescs}${matchedIds.length > 5 ? "..." : ""}`);
      }
    }
  }

  // ══════════════════════════════════════════════════════════════════════
  // SUMMARY
  // ══════════════════════════════════════════════════════════════════════
  console.log("\n\n════════════════════════════════════════════════════════");
  console.log("📊 FRANCHISE DETECTION v2 SUMMARY");
  console.log("════════════════════════════════════════════════════════\n");
  console.log(`  Wikidata:           ${stats.wikidata} franchises`);
  console.log(`  TMDB Collections:   ${stats.tmdb_collection} franchises`);
  console.log(`  Jikan Relations:    ${stats.jikan_relations} franchises`);
  console.log(`  IGDB Franchises:    ${stats.igdb_franchise} franchises`);
  console.log(`  Exact Title Match:  ${stats.exact_title} franchises`);
  console.log(`  Manual Seed:        ${stats.manual} franchises`);
  console.log(`  ───────────────────────────────────────`);
  console.log(`  Total franchises:   ${stats.total_franchises}`);
  console.log(`  Total items linked: ${stats.total_items_linked}`);
  console.log(`  Items NOT linked:   ${items.length - alreadyLinked.size}`);
  console.log(`════════════════════════════════════════════════════════\n`);

  // List popular unlinked items
  const unlinked = items
    .filter((i) => !alreadyLinked.has(i.id))
    .slice(0, 20);
  if (unlinked.length > 0) {
    console.log("Notable items still NOT linked to any franchise:");
    unlinked.forEach((i) => console.log(`  - ${i.title} (${i.type}, ${i.year})`));
  }

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error("Detection failed:", e);
  process.exit(1);
});
