/**
 * Phase 3C: Podcast series grouping — pure SQL, no API needed.
 * Groups podcast items by stripping season/episode markers from titles
 * and linking episodes/seasons of the same show into one franchise.
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

function baseTitle(title: string): string {
  return title
    .replace(/[\s:–—-]+Season\s+\d+.*/i, '')
    .replace(/[\s:–—-]+Episode\s+\d+.*/i, '')
    .replace(/[\s:–—-]+Vol\.?\s+\d+.*/i, '')
    .replace(/[\s:–—-]+Part\s+\d+.*/i, '')
    .replace(/[\s:–—-]+Series\s+\d+.*/i, '')
    .replace(/\s+\d{4}$/,'')        // trailing year
    .replace(/,\s*(Season|Vol)\s+.*/i, '')
    .trim();
}

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 3C: PODCAST SERIES GROUPING');
  console.log('════════════════════════════════════════════════════\n');

  const allPodcasts = await prisma.item.findMany({
    where: { type: 'podcast', isUpcoming: false },
    select: { id: true, title: true, franchiseItems: { select: { franchiseId: true } } },
    orderBy: { title: 'asc' },
  });

  console.log(`Total podcasts: ${allPodcasts.length}`);
  console.log(`Unlinked: ${allPodcasts.filter(p => p.franchiseItems.length === 0).length}\n`);

  // Group by base title
  const groups = new Map<string, typeof allPodcasts>();
  for (const p of allPodcasts) {
    const base = baseTitle(p.title);
    if (!groups.has(base)) groups.set(base, []);
    groups.get(base)!.push(p);
  }

  // Show groups of 2+ for inspection
  const multiGroups = [...groups.entries()].filter(([, items]) => items.length >= 2);
  console.log(`Groups of 2+ items: ${multiGroups.length}`);
  multiGroups.forEach(([base, items]) => {
    console.log(`\n  "${base}" (${items.length} items):`);
    items.forEach(i => console.log(`    [${i.id}] "${i.title}" ${i.franchiseItems.length > 0 ? '(linked)' : ''}`));
  });

  // Execute linking
  let linked = 0, newFranchises = 0;
  for (const [base, items] of multiGroups) {
    if (items.length < 2) continue;

    // Find existing franchise first
    let franchiseId: number | null = null;
    for (const item of items) {
      if (item.franchiseItems.length > 0) {
        franchiseId = item.franchiseItems[0].franchiseId;
        break;
      }
    }
    if (!franchiseId) {
      const existing = await prisma.franchise.findFirst({ where: { name: { equals: base, mode: 'insensitive' } } });
      if (existing) {
        franchiseId = existing.id;
      } else {
        const created = await prisma.franchise.create({
          data: { name: base, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
        });
        franchiseId = created.id;
        newFranchises++;
      }
    }

    for (const item of items) {
      if (item.franchiseItems.length > 0) continue;
      try {
        await prisma.franchiseItem.create({ data: { franchiseId, itemId: item.id, addedBy: 'title_pattern' } });
        linked++;
      } catch { /* dup */ }
    }
  }

  console.log(`\n  ✅ Linked: ${linked} | New franchises: ${newFranchises}`);
  const [total, unlinked] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  console.log(`  Coverage: ${total - unlinked}/${total} (${(((total-unlinked)/total)*100).toFixed(1)}%)`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
