/**
 * Phase 3A: Book series linking via Google Books API seriesInfo.
 * For each book with googleBooksId, fetch series metadata and group
 * books in the same series into franchises.
 * Rate: 100ms between calls (Google Books allows generous limits with API key)
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);
const GB_KEY = process.env.GOOGLE_BOOKS_API_KEY!;

async function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function gbGet(volumeId: string): Promise<any> {
  const url = `https://www.googleapis.com/books/v1/volumes/${volumeId}?fields=volumeInfo(title,seriesInfo,authors)&key=${GB_KEY}`;
  const res = await fetch(url);
  if (res.status === 429) { await sleep(5000); return gbGet(volumeId); }
  if (!res.ok) return null;
  return res.json();
}

async function findOrCreate(name: string): Promise<number> {
  const ex = await prisma.franchise.findFirst({ where: { name: { equals: name, mode: 'insensitive' } } });
  if (ex) return ex.id;
  const c = await prisma.franchise.create({
    data: { name, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
  });
  return c.id;
}

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 3A: GOOGLE BOOKS SERIES LINKING');
  console.log('════════════════════════════════════════════════════\n');

  const books = await prisma.item.findMany({
    where: { type: 'book', googleBooksId: { not: null }, isUpcoming: false },
    select: { id: true, title: true, googleBooksId: true, franchiseItems: { select: { franchiseId: true } } },
  });
  const unlinked = books.filter(b => b.franchiseItems.length === 0);
  console.log(`Books with googleBooksId: ${books.length}, unlinked: ${unlinked.length}\n`);

  // Fetch series info for all unlinked books
  const seriesMap = new Map<string, Array<{ id: number; title: string; bookNum: string }>>(); // seriesTitle → items
  let fetched = 0, withSeries = 0;

  for (const book of unlinked) {
    const data = await gbGet(book.googleBooksId!);
    fetched++;

    if (data?.volumeInfo?.seriesInfo?.shortSeriesBookTitle) {
      const seriesTitle = data.volumeInfo.seriesInfo.shortSeriesBookTitle.trim();
      const bookNum = data.volumeInfo.seriesInfo.bookDisplayNumber || '';
      if (!seriesMap.has(seriesTitle)) seriesMap.set(seriesTitle, []);
      seriesMap.get(seriesTitle)!.push({ id: book.id, title: book.title, bookNum });
      withSeries++;
    }

    if (fetched % 200 === 0) {
      console.log(`  Fetched ${fetched}/${unlinked.length} (${withSeries} in a series so far)`);
    }
    await sleep(100);
  }

  console.log(`\n✅ Scanned ${fetched} books: ${withSeries} belong to a series`);
  console.log(`   Unique series: ${seriesMap.size}\n`);

  // Link series with 2+ books in our DB
  let linked = 0, newFranchises = 0;
  const summaryRows: string[] = [];

  for (const [seriesTitle, items] of seriesMap) {
    if (items.length < 2) continue;

    const franchiseId = await findOrCreate(seriesTitle);
    let groupLinked = 0;

    for (const item of items) {
      try {
        await prisma.franchiseItem.create({ data: { franchiseId, itemId: item.id, addedBy: 'title' } });
        linked++;
        groupLinked++;
      } catch { /* dup */ }
    }

    if (groupLinked > 0) {
      summaryRows.push(`  "${seriesTitle}": +${groupLinked} books`);
    }
  }

  summaryRows.sort().forEach(r => console.log(r));

  console.log(`\n════════════════════════════════════════════════════`);
  console.log(`BOOKS PHASE COMPLETE`);
  console.log(`  Linked: ${linked} | New franchises: ${newFranchises}`);
  const [total, unlinkedCount] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  console.log(`  Coverage: ${total - unlinkedCount}/${total} (${(((total-unlinkedCount)/total)*100).toFixed(1)}%)`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
