/**
 * Phase 2A: Link movies (and TV) to franchises via TMDB collection data
 * Processes all unlinked movies with tmdbId, checks belongs_to_collection,
 * then fetches full collection data to link all matching movies in our DB.
 * Rate: ~100ms between calls (~10 req/s, within TMDB's 40/10s limit)
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);
const TMDB_KEY = process.env.TMDB_API_KEY!;

async function tmdbGet(path: string): Promise<any> {
  const sep = path.includes('?') ? '&' : '?';
  const url = `https://api.themoviedb.org/3${path}${sep}api_key=${TMDB_KEY}`;
  const res = await fetch(url);
  if (res.status === 429) {
    console.log('  Rate limited, waiting 5s...');
    await sleep(5000);
    return tmdbGet(path);
  }
  if (!res.ok) return null;
  return res.json();
}

async function sleep(ms: number) {
  return new Promise(r => setTimeout(r, ms));
}

async function findOrCreateFranchise(name: string): Promise<number> {
  const existing = await prisma.franchise.findFirst({
    where: { name: { equals: name, mode: 'insensitive' } },
  });
  if (existing) return existing.id;

  const created = await prisma.franchise.create({
    data: { name, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
  });
  return created.id;
}

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 2A: TMDB COLLECTION LINKING (Movies + TV)');
  console.log('════════════════════════════════════════════════════\n');

  // Build tmdbId → itemId map for fast lookup
  const allMovies = await prisma.item.findMany({
    where: { type: 'movie', tmdbId: { not: null }, isUpcoming: false },
    select: { id: true, title: true, tmdbId: true, franchiseItems: { select: { franchiseId: true } } },
  });
  const allTv = await prisma.item.findMany({
    where: { type: 'tv', tmdbId: { not: null }, isUpcoming: false },
    select: { id: true, title: true, tmdbId: true, franchiseItems: { select: { franchiseId: true } } },
  });

  console.log(`Movies with tmdbId: ${allMovies.length} (${allMovies.filter(m => m.franchiseItems.length === 0).length} unlinked)`);
  console.log(`TV with tmdbId: ${allTv.length} (${allTv.filter(t => t.franchiseItems.length === 0).length} unlinked)\n`);

  // tmdbId → db item map (for linking movies we find in collections)
  const tmdbIdToMovie = new Map<number, { id: number; title: string; linked: boolean }>();
  for (const m of allMovies) tmdbIdToMovie.set(m.tmdbId!, { id: m.id, title: m.title, linked: m.franchiseItems.length > 0 });

  // ───────────────────────────────
  // MOVIES: Check belongs_to_collection
  // ───────────────────────────────
  const unlinkedMovies = allMovies.filter(m => m.franchiseItems.length === 0);
  const collectionMap = new Map<number, { name: string; tmdbCollectionId: number; itemIds: number[] }>();
  // Also track collections we already know about (from linked movies)
  const processedCollections = new Set<number>();

  console.log(`Processing ${unlinkedMovies.length} unlinked movies...`);
  let processed = 0;
  let withCollection = 0;

  for (const movie of unlinkedMovies) {
    const data = await tmdbGet(`/movie/${movie.tmdbId}`);
    processed++;

    if (data?.belongs_to_collection) {
      const col = data.belongs_to_collection;
      withCollection++;
      if (!collectionMap.has(col.id)) {
        collectionMap.set(col.id, { name: col.name, tmdbCollectionId: col.id, itemIds: [] });
      }
      collectionMap.get(col.id)!.itemIds.push(movie.id);
    }

    if (processed % 200 === 0) {
      console.log(`  Progress: ${processed}/${unlinkedMovies.length} (${withCollection} in collections so far)`);
    }

    await sleep(100);
  }

  console.log(`\n✅ Movie scan complete: ${withCollection}/${unlinkedMovies.length} belong to a TMDB collection`);
  console.log(`   Unique collections found: ${collectionMap.size}\n`);

  // ───────────────────────────────
  // For each collection: fetch full movie list + link to franchise
  // ───────────────────────────────
  let totalLinked = 0;
  let newFranchises = 0;
  const franchiseSummary: Map<string, number> = new Map();

  // Filter to collections with 2+ of our movies (more reliable)
  // But also process collections with 1 if the collection has other movies in our DB by tmdbId
  const collectionsToProcess = [...collectionMap.values()];
  console.log(`Processing ${collectionsToProcess.length} collections...`);

  for (const col of collectionsToProcess) {
    if (processedCollections.has(col.tmdbCollectionId)) continue;
    processedCollections.add(col.tmdbCollectionId);

    // Fetch full collection data
    const colData = await tmdbGet(`/collection/${col.tmdbCollectionId}`);
    await sleep(100);

    if (!colData || !colData.parts) continue;

    // Find all movies in this collection that are in our DB
    const matchingItemIds = new Set<number>(col.itemIds);
    for (const part of colData.parts) {
      const dbItem = tmdbIdToMovie.get(part.id);
      if (dbItem) matchingItemIds.add(dbItem.id);
    }

    if (matchingItemIds.size < 2) continue; // Only create franchise if 2+ movies match

    // Find or create franchise
    const franchiseName = col.name.replace(/ Collection$/i, '').replace(/ Franchise$/i, '').trim();
    const franchiseId = await findOrCreateFranchise(franchiseName);
    if (franchiseName !== col.name) newFranchises++;
    else {
      // Check if this was freshly created
      const existing = await prisma.franchise.findFirst({ where: { name: { equals: franchiseName, mode: 'insensitive' } } });
      if (!existing) newFranchises++;
    }

    // Link all matching movies
    let colLinked = 0;
    for (const itemId of matchingItemIds) {
      try {
        await prisma.franchiseItem.create({
          data: { franchiseId, itemId, addedBy: 'tmdb' },
        });
        colLinked++;
        totalLinked++;
      } catch {
        // Already linked
      }
    }

    if (colLinked > 0) {
      franchiseSummary.set(franchiseName, (franchiseSummary.get(franchiseName) || 0) + colLinked);
    }
  }

  // ───────────────────────────────
  // TV SHOWS: Use TMDB series info
  // ───────────────────────────────
  // For TV, TMDB doesn't have "belongs_to_collection" like movies
  // But we can check if TV shows belong to a franchise using the show's title-based links
  // We already handled anime seasons via Phase 1D title matching
  // For remaining TV, skip (Phase 2D/Jikan will handle anime, others need different approach)

  // ───────────────────────────────
  // Summary
  // ───────────────────────────────
  console.log('\n════════════════════════════════════════════════════');
  console.log('TMDB PHASE COMPLETE');
  console.log('════════════════════════════════════════════════════');
  console.log(`  New franchise links: ${totalLinked}`);

  const sorted = [...franchiseSummary.entries()].sort((a, b) => b[1] - a[1]);
  console.log('\n  Franchises linked (top 40):');
  sorted.slice(0, 40).forEach(([name, count]) => console.log(`    "${name}": +${count} movies`));
  if (sorted.length > 40) console.log(`    ... and ${sorted.length - 40} more`);

  const [total, unlinked] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  const linkedTotal = total - unlinked;
  console.log(`\n  Items with franchise: ${linkedTotal}/${total} (${((linkedTotal/total)*100).toFixed(1)}%)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
