/**
 * Phase 3F: TV/anime season grouping via title-based pattern matching.
 * Strips season/part/cour markers from titles and groups matching shows.
 * Handles: "Season 2", "2nd Season", "Final Season", "Part 2", " 2" (sequel suffix).
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

function baseTitle(t: string): string {
  return t
    .replace(/[\s:,–—]+Season\s+\d+(\s+Part\s+\d+)?$/i, '')
    .replace(/[\s:,–—]+(?:\d+(?:st|nd|rd|th)|Final|The Final)\s+Season$/i, '')
    .replace(/[\s:,–—]+Part\s+\d+(\s+Cour\s+\d+)?$/i, '')
    .replace(/[\s:,–—]+\d+(?:st|nd|rd|th)\s+Cour$/i, '')
    .replace(/[\s:,–—]+Cour\s+\d+$/i, '')
    .replace(/\s+[2-9]$/, '')  // Single-digit sequel suffix (e.g. "Berserk 2", "Psycho-Pass 3")
    .trim();
}

// Known false-positive base titles to skip
const SKIP_BASES = new Set([
  'the', 'extra', 'monster', 'kingdom', 'mission', 'special',
  'the seasons', 'ova', 'movie', 'film',
]);

async function findOrCreate(name: string, newFranchisesRef: { count: number }): Promise<number> {
  const ex = await prisma.franchise.findFirst({ where: { name: { equals: name, mode: 'insensitive' } } });
  if (ex) return ex.id;
  newFranchisesRef.count++;
  return (await prisma.franchise.create({
    data: { name, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
  })).id;
}

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 3F: TV SEASON TITLE GROUPING');
  console.log('════════════════════════════════════════════════════\n');

  const allTv = await prisma.item.findMany({
    where: { type: 'tv', isUpcoming: false },
    select: { id: true, title: true, franchiseItems: { select: { franchiseId: true } } },
  });

  console.log(`Total TV items: ${allTv.length}`);
  console.log(`Unlinked: ${allTv.filter(t => t.franchiseItems.length === 0).length}\n`);

  // Group by base title
  const groups = new Map<string, typeof allTv>();
  for (const tv of allTv) {
    const base = baseTitle(tv.title);
    if (base.length < 4) continue;  // skip very short bases
    if (SKIP_BASES.has(base.toLowerCase())) continue;
    if (!groups.has(base)) groups.set(base, []);
    groups.get(base)!.push(tv);
  }

  // Groups with 2+ items that have at least 1 unlinked
  const actionable = [...groups.entries()].filter(([, items]) =>
    items.length >= 2 && items.some(i => i.franchiseItems.length === 0)
  );
  console.log(`Actionable groups (2+ items, 1+ unlinked): ${actionable.length}\n`);

  let linked = 0;
  const newFranchisesRef = { count: 0 };

  for (const [base, items] of actionable) {
    // Find existing franchise from already-linked items in the group
    let franchiseId: number | null = null;
    for (const item of items) {
      if (item.franchiseItems.length > 0) {
        franchiseId = item.franchiseItems[0].franchiseId;
        break;
      }
    }

    if (!franchiseId) {
      franchiseId = await findOrCreate(base, newFranchisesRef);
    }

    let groupLinked = 0;
    for (const item of items) {
      if (item.franchiseItems.length > 0) continue;
      try {
        await prisma.franchiseItem.create({
          data: { franchiseId, itemId: item.id, addedBy: 'title_pattern' },
        });
        linked++;
        groupLinked++;
      } catch { /* dup */ }
    }

    if (groupLinked > 0) {
      const linkedCount = items.filter(i => i.franchiseItems.length > 0).length;
      const tag = linkedCount > 0 ? '🔗' : '✅';
      console.log(`  ${tag} "${base}": +${groupLinked} items linked`);
      items.forEach(i => {
        const wasLinked = i.franchiseItems.length > 0;
        const nowLinked = !wasLinked && groupLinked > 0;
        console.log(`      ${wasLinked ? '✅' : nowLinked ? '🆕' : '⬜'} "${i.title}"`);
      });
    }
  }

  console.log(`\n════════════════════════════════════════════════════`);
  console.log(`TV TITLE GROUPING COMPLETE`);
  console.log(`  Linked: ${linked} | New franchises: ${newFranchisesRef.count}`);
  const [total, unlinkedCount] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  console.log(`  Coverage: ${total - unlinkedCount}/${total} (${(((total - unlinkedCount) / total) * 100).toFixed(1)}%)`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
