/**
 * Phase 3B: TV show grouping via TMDB show IDs
 * For each unlinked TV item with tmdbId, fetch the show's canonical name
 * from TMDB (which strips season numbers). Group items with same show name
 * into franchises. Also groups by malId for anime shows.
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);
const TMDB_KEY = process.env.TMDB_API_KEY!;

async function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function tmdbGet(path: string): Promise<any> {
  const sep = path.includes('?') ? '&' : '?';
  const res = await fetch(`https://api.themoviedb.org/3${path}${sep}api_key=${TMDB_KEY}`);
  if (res.status === 429) { await sleep(5000); return tmdbGet(path); }
  if (!res.ok) return null;
  return res.json();
}

async function findOrCreate(name: string): Promise<number> {
  const ex = await prisma.franchise.findFirst({ where: { name: { equals: name, mode: 'insensitive' } } });
  if (ex) return ex.id;
  const c = await prisma.franchise.create({
    data: { name, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
  });
  newFranchises++;
  return c.id;
}

let newFranchises = 0;

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 3B: TV SHOW GROUPING VIA TMDB');
  console.log('════════════════════════════════════════════════════\n');

  const allTv = await prisma.item.findMany({
    where: { type: 'tv', tmdbId: { not: null }, isUpcoming: false },
    select: { id: true, title: true, tmdbId: true, franchiseItems: { select: { franchiseId: true } } },
  });
  const unlinked = allTv.filter(t => t.franchiseItems.length === 0);
  console.log(`TV with tmdbId: ${allTv.length}, unlinked: ${unlinked.length}\n`);

  // Step 1: Fetch canonical show name from TMDB for each unlinked TV item
  // tmdbId on TV items is the TMDB show ID (not season ID)
  // GET /tv/{id} returns { name, original_name, ... }
  const tmdbNameMap = new Map<number, string>(); // tmdbId → canonical show name
  let fetched = 0;

  for (const tv of unlinked) {
    const data = await tmdbGet(`/tv/${tv.tmdbId}`);
    fetched++;
    if (data?.name) {
      // Strip common season suffix patterns from our stored title to get the base name
      // Use TMDB's canonical name directly (it's always just the show name, no season)
      tmdbNameMap.set(tv.tmdbId!, data.name);
    }
    if (fetched % 200 === 0) console.log(`  Fetched ${fetched}/${unlinked.length}...`);
    await sleep(80);
  }
  console.log(`\nGot show names for ${tmdbNameMap.size} TV items`);

  // Step 2: Also check LINKED TV items' tmdbIds to see what show names they have
  // (so we can link unlinked seasons to already-franchised shows)
  const linkedTv = allTv.filter(t => t.franchiseItems.length > 0);
  const linkedTmdbNames = new Map<string, number>(); // show name → franchiseId
  for (const tv of linkedTv) {
    if (!tv.tmdbId) continue;
    const data = await tmdbGet(`/tv/${tv.tmdbId}`);
    if (data?.name) linkedTmdbNames.set(data.name.toLowerCase(), tv.franchiseItems[0].franchiseId);
    await sleep(80);
  }
  console.log(`Got show names for ${linkedTmdbNames.size} already-linked TV items`);

  // Step 3: Group unlinked TV items by canonical show name
  const showGroups = new Map<string, Array<{ id: number; title: string }>>();
  for (const tv of unlinked) {
    const name = tmdbNameMap.get(tv.tmdbId!);
    if (!name) continue;
    if (!showGroups.has(name)) showGroups.set(name, []);
    showGroups.get(name)!.push({ id: tv.id, title: tv.title });
  }

  // Step 4: Link groups of 2+ items OR items matching an existing franchise show name
  let linked = 0;
  let groupsLinked = 0;

  for (const [showName, items] of showGroups) {
    // Check if this show name matches an already-linked franchise
    let franchiseId: number | null = linkedTmdbNames.get(showName.toLowerCase()) || null;

    if (!franchiseId && items.length < 2) continue; // skip singletons with no existing franchise

    if (!franchiseId) {
      franchiseId = await findOrCreate(showName);
      groupsLinked++;
    }

    for (const item of items) {
      try {
        await prisma.franchiseItem.create({ data: { franchiseId, itemId: item.id, addedBy: 'tmdb' } });
        linked++;
        console.log(`  ✅ [tv] "${item.title}" → "${showName}"`);
      } catch { /* dup */ }
    }
  }

  console.log(`\n════════════════════════════════════════════════════`);
  console.log(`TV TMDB COMPLETE`);
  console.log(`  Linked: ${linked} | New franchises: ${newFranchises} | Groups linked: ${groupsLinked}`);
  const [total, unlinked2] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  console.log(`  Coverage: ${total - unlinked2}/${total} (${(((total-unlinked2)/total)*100).toFixed(1)}%)`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
