/**
 * Phase 3E: Music discography grouping via Spotify artist data.
 * Groups albums by the same artist into artist franchise entries.
 * Also links music items that share a spotifyId prefix (same album family).
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

const SP_CLIENT_ID = process.env.SPOTIFY_CLIENT_ID!;
const SP_CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET!;
let spToken = '';

async function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function getSpotifyToken(): Promise<string> {
  const creds = Buffer.from(`${SP_CLIENT_ID}:${SP_CLIENT_SECRET}`).toString('base64');
  const res = await fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: { 'Authorization': `Basic ${creds}`, 'Content-Type': 'application/x-www-form-urlencoded' },
    body: 'grant_type=client_credentials',
  });
  const data = await res.json() as any;
  return data.access_token;
}

async function spotifyGet(path: string): Promise<any> {
  const res = await fetch(`https://api.spotify.com/v1${path}`, {
    headers: { 'Authorization': `Bearer ${spToken}` },
  });
  if (res.status === 401) { spToken = await getSpotifyToken(); return spotifyGet(path); }
  if (res.status === 429) { await sleep(3000); return spotifyGet(path); }
  if (!res.ok) return null;
  return res.json();
}

async function findOrCreate(name: string): Promise<number> {
  const ex = await prisma.franchise.findFirst({ where: { name: { equals: name, mode: 'insensitive' } } });
  if (ex) return ex.id;
  return (await prisma.franchise.create({
    data: { name, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
  })).id;
}

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 3E: MUSIC DISCOGRAPHY GROUPING');
  console.log('════════════════════════════════════════════════════\n');

  spToken = await getSpotifyToken();

  const allMusic = await prisma.item.findMany({
    where: { type: 'music', isUpcoming: false },
    select: {
      id: true, title: true, spotifyId: true, people: true,
      franchiseItems: { select: { franchiseId: true } },
    },
  });
  const unlinked = allMusic.filter(m => m.franchiseItems.length === 0);
  console.log(`Music: ${allMusic.length} total, ${unlinked.length} unlinked\n`);

  // Strategy 1: Group by primary artist name from `people` field
  const artistGroups = new Map<string, Array<{ id: number; title: string }>>();

  for (const item of unlinked) {
    const people = item.people as any[];
    if (!Array.isArray(people) || people.length === 0) continue;
    // Find artist/performer
    const artist = people.find((p: any) =>
      p.role === 'Artist' || p.role === 'Band' || p.role === 'Performer' ||
      p.role === 'Primary Artist' || p.role === 'Main Artist'
    ) || people[0];
    if (!artist?.name || artist.name.length < 2) continue;

    const key = artist.name.trim();
    if (!artistGroups.has(key)) artistGroups.set(key, []);
    artistGroups.get(key)!.push({ id: item.id, title: item.title });
  }

  console.log(`Artist groups found: ${artistGroups.size}`);
  const multiArtist = [...artistGroups.entries()].filter(([, items]) => items.length >= 2);
  console.log(`Artists with 2+ albums: ${multiArtist.length}\n`);

  // Strategy 2: For music items with spotifyId, fetch Spotify artist info to confirm artist name
  // and get all their albums that might be in our DB
  // (Only do this for artists with 2+ albums already, to avoid expensive API calls for solo items)
  const artistAlbumMap = new Map<string, string[]>(); // artistName → all their spotifyAlbumIds

  if (unlinked.some(m => m.spotifyId)) {
    // Sample a few to understand the data structure
    const sampleWithSpotify = unlinked.filter(m => m.spotifyId).slice(0, 5);
    for (const item of sampleWithSpotify) {
      const data = await spotifyGet(`/albums/${item.spotifyId}`);
      if (data?.artists?.[0]) {
        console.log(`Sample: "${item.title}" → artist: "${data.artists[0].name}"`);
      }
      await sleep(200);
    }
  }

  // Link artist groups of 2+ albums
  let linked = 0, newFranchises = 0;
  for (const [artistName, items] of multiArtist) {
    // Skip generic/label names
    if (artistName.length < 3) continue;
    if (['Various Artists', 'Various', 'Unknown Artist', 'Soundtrack'].includes(artistName)) continue;

    const franchiseId = await findOrCreate(artistName);
    let groupLinked = 0;

    for (const item of items) {
      try {
        await prisma.franchiseItem.create({ data: { franchiseId, itemId: item.id, addedBy: 'auto_pattern' } });
        linked++;
        groupLinked++;
      } catch { /* dup */ }
    }

    if (groupLinked > 0) {
      console.log(`  ✅ "${artistName}": +${groupLinked} albums`);
    }
  }

  console.log(`\n════════════════════════════════════════════════════`);
  console.log(`MUSIC PHASE COMPLETE`);
  console.log(`  Linked: ${linked} | New franchises: ${newFranchises}`);
  const [total, unlinkedCount] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  console.log(`  Coverage: ${total - unlinkedCount}/${total} (${(((total-unlinkedCount)/total)*100).toFixed(1)}%)`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
