/**
 * Phase 3G: Book series linking via OpenLibrary work subjects.
 *
 * Strategy (confirmed working via manual testing):
 *   1. Group unlinked books by author — only process authors with 2+ books
 *      (a series can only be detected if we have 2+ books in DB anyway)
 *   2. For each book, search OL by title+author → get work key
 *   3. Fetch work.json → extract subjects matching "series:Name" pattern
 *   4. Group books by normalized series name
 *   5. Create franchise for groups of 2+
 *
 * Rate: 1 call per second — two calls per book (search + work fetch).
 * User-Agent required. No API key needed.
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

const UA = 'LiteracyApp/1.0 (book-series-linking; github.com/literacy-app)';
const DELAY = 1100; // 1.1s — slightly above 1 req/s limit

async function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function olSearch(title: string, author?: string): Promise<string | null> {
  const params = new URLSearchParams({
    title: title.slice(0, 120),
    fields: 'key',
    limit: '1',
  });
  if (author) params.set('author', author.slice(0, 80));

  try {
    const res = await fetch(`https://openlibrary.org/search.json?${params}`, {
      headers: { 'User-Agent': UA },
    });
    if (!res.ok) return null;
    const data = await res.json() as any;
    return data?.docs?.[0]?.key ?? null; // e.g. "/works/OL12345W"
  } catch {
    return null;
  }
}

async function olWork(workKey: string): Promise<string[]> {
  // workKey is like "/works/OL12345W"
  try {
    const res = await fetch(`https://openlibrary.org${workKey}.json`, {
      headers: { 'User-Agent': UA },
    });
    if (!res.ok) return [];
    const data = await res.json() as any;
    const subjects: string[] = data?.subjects ?? [];
    // Extract "series:Name" subjects
    return subjects
      .filter((s: string) => s.toLowerCase().startsWith('series:'))
      .map((s: string) => s.slice('series:'.length).replace(/_/g, ' ').trim());
  } catch {
    return [];
  }
}

function normalizeSeriesName(s: string): string {
  // Strip trailing " #N" or " (N)" numbering that sometimes appears
  return s
    .replace(/\s*#\d+$/, '')
    .replace(/\s*\(\d+\)$/, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function toDisplayName(normalized: string): string {
  // Title-case each word
  return normalized.replace(/\b\w/g, c => c.toUpperCase());
}

async function findOrCreate(name: string, newRef: { n: number }): Promise<number> {
  const ex = await prisma.franchise.findFirst({
    where: { name: { equals: name, mode: 'insensitive' } },
  });
  if (ex) return ex.id;
  newRef.n++;
  return (await prisma.franchise.create({
    data: { name, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
  })).id;
}

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 3G: BOOK SERIES LINKING VIA OPENLIBRARY');
  console.log('════════════════════════════════════════════════════\n');

  // Load all unlinked books with author data
  const allBooks = await prisma.item.findMany({
    where: { type: 'book', franchiseItems: { none: {} }, isUpcoming: false },
    select: { id: true, title: true, people: true, voteCount: true },
    orderBy: { voteCount: 'desc' },
  });

  console.log(`Total unlinked books: ${allBooks.length}`);

  // Group by author — extract primary author from people field
  type BookEntry = { id: number; title: string; voteCount: number };
  const byAuthor = new Map<string, BookEntry[]>();

  for (const b of allBooks) {
    const people = (b.people as any[]) || [];
    const authorEntry = people.find((p: any) =>
      ['Author', 'author', 'Writer', 'writer'].includes(p.role)
    ) ?? people[0];
    const author = authorEntry?.name?.trim();
    if (!author || author.length < 2) continue;
    if (!byAuthor.has(author)) byAuthor.set(author, []);
    byAuthor.get(author)!.push({ id: b.id, title: b.title, voteCount: b.voteCount || 0 });
  }

  // Only process authors with 2+ books — singletons can't form a series in our DB
  const multiAuthorBooks = [...byAuthor.entries()]
    .filter(([, books]) => books.length >= 2)
    .sort((a, b) => b[1].length - a[1].length);

  const totalToProcess = multiAuthorBooks.reduce((sum, [, b]) => sum + b.length, 0);
  console.log(`Authors with 2+ books: ${multiAuthorBooks.length}`);
  console.log(`Books to look up: ${totalToProcess}`);
  console.log(`Estimated time (2 OL calls/book): ~${Math.ceil(totalToProcess * 2 / 60)} min\n`);

  // Map: normalized series name → book entries
  const seriesMap = new Map<string, BookEntry[]>();
  // Also track raw display names for each series key
  const seriesDisplayName = new Map<string, string>();

  let totalFetched = 0;
  let withSeries = 0;
  let apiErrors = 0;

  for (const [author, books] of multiAuthorBooks) {
    for (const book of books) {
      // Step 1: Search for work key
      const workKey = await olSearch(book.title, author);
      totalFetched++;
      await sleep(DELAY);

      if (!workKey) {
        apiErrors++;
        if (totalFetched % 50 === 0) {
          console.log(`  [${totalFetched}/${totalToProcess}] ${withSeries} series hits, ${apiErrors} misses`);
        }
        continue;
      }

      // Step 2: Fetch work subjects
      const seriesNames = await olWork(workKey);
      totalFetched++;
      await sleep(DELAY);

      if (seriesNames.length > 0) {
        // Use the shortest series name (most general)
        const best = seriesNames.sort((a, b) => a.length - b.length)[0];
        const key = normalizeSeriesName(best);
        if (key.length >= 3) {
          if (!seriesMap.has(key)) {
            seriesMap.set(key, []);
            seriesDisplayName.set(key, best);
          }
          seriesMap.get(key)!.push(book);
          withSeries++;
        }
      }

      if (totalFetched % 100 === 0) {
        console.log(`  [${totalFetched}/${totalToProcess * 2}] Fetched ${totalFetched / 2} books — ${withSeries} in series, ${apiErrors} search misses`);
      }
    }
  }

  console.log(`\n✅ Lookup complete:`);
  console.log(`   Books looked up: ${Math.round(totalFetched / 2)}`);
  console.log(`   With series data: ${withSeries}`);
  console.log(`   Unique series: ${seriesMap.size}`);

  // Only link series with 2+ books in DB
  const actionable = [...seriesMap.entries()].filter(([, books]) => books.length >= 2);
  console.log(`   Series with 2+ DB matches: ${actionable.length}\n`);

  let linked = 0;
  const newRef = { n: 0 };

  for (const [key, books] of actionable) {
    const rawDisplay = seriesDisplayName.get(key) ?? '';
    const displayName = toDisplayName(rawDisplay || key);

    // Deduplicate books (a book could match multiple series subjects)
    const seen = new Set<number>();
    const uniqueBooks = books.filter(b => {
      if (seen.has(b.id)) return false;
      seen.add(b.id);
      return true;
    });

    if (uniqueBooks.length < 2) continue;

    const franchiseId = await findOrCreate(displayName, newRef);
    let groupLinked = 0;

    for (const book of uniqueBooks) {
      try {
        await prisma.franchiseItem.create({
          data: { franchiseId, itemId: book.id, addedBy: 'openlibrary' },
        });
        linked++;
        groupLinked++;
      } catch { /* dup */ }
    }

    if (groupLinked > 0) {
      console.log(`  ✅ "${displayName}": +${groupLinked} books`);
      uniqueBooks.forEach(b => console.log(`      [${b.id}] "${b.title}"`));
    }
  }

  console.log(`\n════════════════════════════════════════════════════`);
  console.log(`OPENLIBRARY PHASE COMPLETE`);
  console.log(`  Linked: ${linked} | New franchises: ${newRef.n}`);
  const [total, unlinkedCount] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  console.log(`  Coverage: ${total - unlinkedCount}/${total} (${(((total - unlinkedCount) / total) * 100).toFixed(1)}%)`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
