/**
 * Phase 2B: Link games to franchises via IGDB franchise + collection data
 * IGDB allows batch queries of 500 items — very fast.
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

const IGDB_CLIENT_ID = process.env.IGDB_CLIENT_ID!;
const IGDB_CLIENT_SECRET = process.env.IGDB_CLIENT_SECRET!;
let igdbToken = '';

async function getIgdbToken(): Promise<string> {
  const res = await fetch(
    `https://id.twitch.tv/oauth2/token?client_id=${IGDB_CLIENT_ID}&client_secret=${IGDB_CLIENT_SECRET}&grant_type=client_credentials`,
    { method: 'POST' }
  );
  const data = await res.json() as any;
  return data.access_token;
}

async function igdbQuery(endpoint: string, body: string): Promise<any[]> {
  const res = await fetch(`https://api.igdb.com/v4/${endpoint}`, {
    method: 'POST',
    headers: {
      'Client-ID': IGDB_CLIENT_ID,
      'Authorization': `Bearer ${igdbToken}`,
      'Content-Type': 'text/plain',
    },
    body,
  });
  if (!res.ok) {
    console.error(`IGDB ${endpoint} error: ${res.status} ${await res.text()}`);
    return [];
  }
  return res.json() as any;
}

async function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// Find or create a Literacy franchise by name
async function findOrCreateFranchise(name: string, igdbSourceId?: number, isCollection = false): Promise<number> {
  // Try exact match first
  let franchise = await prisma.franchise.findFirst({
    where: { name: { equals: name, mode: 'insensitive' } },
  });
  if (franchise) return franchise.id;

  // Create new
  franchise = await prisma.franchise.create({
    data: {
      name,
      autoGenerated: true,
      confidenceTier: 1,
      description: '',
      icon: '',
      cover: '',
    },
  });
  return franchise.id;
}

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 2B: IGDB FRANCHISE LINKING');
  console.log('════════════════════════════════════════════════════\n');

  // Get auth token
  igdbToken = await getIgdbToken();
  console.log('✅ IGDB auth token obtained\n');

  // Step 1: Get all igdbIds from games in our DB (unlinked only for linking, but also check linked to fill gaps)
  const allGames = await prisma.item.findMany({
    where: { type: 'game', igdbId: { not: null }, isUpcoming: false },
    select: {
      id: true, title: true, igdbId: true,
      franchiseItems: { select: { franchiseId: true } },
    },
  });

  const unlinkedGames = allGames.filter(g => g.franchiseItems.length === 0);
  console.log(`Games with igdbId: ${allGames.length}`);
  console.log(`Unlinked games with igdbId: ${unlinkedGames.length}\n`);

  // Step 2: Batch query IGDB for franchise + collection data (500 at a time)
  const igdbIds = unlinkedGames.map(g => g.igdbId!);
  const batches: number[][] = [];
  for (let i = 0; i < igdbIds.length; i += 500) batches.push(igdbIds.slice(i, i + 500));

  console.log(`Processing ${batches.length} IGDB batch(es) of up to 500 games each...`);

  const igdbGameMap: Map<number, { franchise?: number; franchises?: number[]; collection?: number }> = new Map();

  for (let bi = 0; bi < batches.length; bi++) {
    const batch = batches[bi];
    const query = `fields id, franchise, franchises, collection; where id = (${batch.join(',')}); limit 500;`;
    const results = await igdbQuery('games', query);
    for (const r of results) {
      igdbGameMap.set(r.id, {
        franchise: r.franchise,
        franchises: r.franchises,
        collection: r.collection,
      });
    }
    console.log(`  Batch ${bi + 1}/${batches.length}: got data for ${results.length} games`);
    if (bi < batches.length - 1) await sleep(300);
  }

  // Step 3: Collect all unique franchise IDs and collection IDs
  const franchiseIds = new Set<number>();
  const collectionIds = new Set<number>();

  for (const [, data] of igdbGameMap) {
    if (data.franchise) franchiseIds.add(data.franchise);
    if (data.franchises) data.franchises.forEach(id => franchiseIds.add(id));
    if (data.collection) collectionIds.add(data.collection);
  }

  console.log(`\nUnique IGDB franchise IDs: ${franchiseIds.size}`);
  console.log(`Unique IGDB collection IDs: ${collectionIds.size}`);

  // Step 4: Fetch franchise names from IGDB
  const franchiseNameMap = new Map<number, string>(); // igdbFranchiseId → name
  const franchiseIdArr = [...franchiseIds];
  for (let i = 0; i < franchiseIdArr.length; i += 500) {
    const batch = franchiseIdArr.slice(i, i + 500);
    const results = await igdbQuery('franchises', `fields id, name; where id = (${batch.join(',')}); limit 500;`);
    results.forEach(r => franchiseNameMap.set(r.id, r.name));
    if (i + 500 < franchiseIdArr.length) await sleep(300);
  }

  // Step 5: Fetch collection names from IGDB
  const collectionNameMap = new Map<number, string>(); // igdbCollectionId → name
  const collectionIdArr = [...collectionIds];
  for (let i = 0; i < collectionIdArr.length; i += 500) {
    const batch = collectionIdArr.slice(i, i + 500);
    const results = await igdbQuery('collections', `fields id, name; where id = (${batch.join(',')}); limit 500;`);
    results.forEach(r => collectionNameMap.set(r.id, r.name));
    if (i + 500 < collectionIdArr.length) await sleep(300);
  }

  console.log(`\nFetched ${franchiseNameMap.size} franchise names, ${collectionNameMap.size} collection names`);

  // Step 6: Link games to franchises
  // Strategy: prefer franchise over collection (franchise is broader)
  // Build a map from igdbId → best franchise name to use
  let linked = 0;
  let newFranchisesCreated = 0;
  const franchiseSummary: Map<string, number> = new Map(); // franchise name → count linked

  const buildDb = await prisma.franchise.findMany({ select: { id: true, name: true } });
  const dbFranchiseByName = new Map(buildDb.map(f => [f.name.toLowerCase(), f.id]));

  for (const game of unlinkedGames) {
    const igdbData = igdbGameMap.get(game.igdbId!);
    if (!igdbData) continue;

    // Pick the best franchise name: prefer main franchise, fall back to collection
    let franchiseName: string | null = null;
    if (igdbData.franchise && franchiseNameMap.has(igdbData.franchise)) {
      franchiseName = franchiseNameMap.get(igdbData.franchise)!;
    } else if (igdbData.franchises && igdbData.franchises.length > 0) {
      // Take first franchise
      const fid = igdbData.franchises.find(id => franchiseNameMap.has(id));
      if (fid) franchiseName = franchiseNameMap.get(fid)!;
    } else if (igdbData.collection && collectionNameMap.has(igdbData.collection)) {
      franchiseName = collectionNameMap.get(igdbData.collection)!;
    }

    if (!franchiseName) continue;

    // Skip single-game franchise names that exactly match the game title (pointless franchise)
    if (franchiseName.toLowerCase() === game.title.toLowerCase()) continue;

    // Find or create the Literacy franchise
    let literacyFranchiseId = dbFranchiseByName.get(franchiseName.toLowerCase());
    if (!literacyFranchiseId) {
      const newF = await prisma.franchise.create({
        data: { name: franchiseName, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
      });
      literacyFranchiseId = newF.id;
      dbFranchiseByName.set(franchiseName.toLowerCase(), newF.id);
      newFranchisesCreated++;
    }

    // Link the game
    try {
      await prisma.franchiseItem.create({
        data: { franchiseId: literacyFranchiseId, itemId: game.id, addedBy: 'igdb' },
      });
      linked++;
      franchiseSummary.set(franchiseName, (franchiseSummary.get(franchiseName) || 0) + 1);
    } catch {
      // Unique constraint violation = already linked
    }
  }

  // Also: for games already in a franchise, try to link other games with same IGDB franchise
  // that might be in our DB but not yet linked
  console.log('\n─── Filling gaps in existing franchises ───');
  // (already covered by processing all unlinked games above)

  // Step 7: Summary
  console.log('\n════════════════════════════════════════════════════');
  console.log('IGDB PHASE COMPLETE');
  console.log('════════════════════════════════════════════════════');
  console.log(`  New franchise links: ${linked}`);
  console.log(`  New franchises created: ${newFranchisesCreated}`);

  // Show top franchises by items linked
  const sorted = [...franchiseSummary.entries()].sort((a, b) => b[1] - a[1]);
  console.log('\n  Top franchises by items linked:');
  sorted.slice(0, 30).forEach(([name, count]) => console.log(`    "${name}": +${count} games`));
  if (sorted.length > 30) console.log(`    ... and ${sorted.length - 30} more franchises`);

  // Coverage report
  const [total, unlinked] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  const linkedTotal = total - unlinked;
  console.log(`\n  Items with franchise: ${linkedTotal}/${total} (${((linkedTotal/total)*100).toFixed(1)}%)`);
  console.log(`  Was: 1,579/22,475 (7.0%)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
