/**
 * Phase 2D v2: Manga + Anime series linking via Jikan
 * Conservative rate limiting: 1 req/s (well under Jikan's 3/s + 60/min limits)
 * Uses exponential backoff on 429s.
 * Processes only items where related series exist in our DB.
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

const JIKAN_BASE = 'https://api.jikan.moe/v4';
const DELAY_MS = 1100; // 1 req/s - very conservative

async function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function jikanGet(path: string, retryCount = 0): Promise<any> {
  if (retryCount > 0) await sleep(Math.min(30000, 5000 * retryCount)); // exponential backoff, max 30s
  const res = await fetch(`${JIKAN_BASE}${path}`, { headers: { 'Accept': 'application/json' } });
  if (res.status === 429) {
    if (retryCount >= 5) { console.log(`  Giving up on ${path} after 5 retries`); return null; }
    return jikanGet(path, retryCount + 1);
  }
  if (!res.ok) return null;
  return res.json();
}

const LINK_RELATION_TYPES = new Set([
  'Sequel', 'Prequel', 'Side Story', 'Alternative Version', 'Full Story', 'Summary',
]);

async function main() {
  console.log('════════════════════════════════════════════════════');
  console.log('PHASE 2D v2: JIKAN/MAL SERIES LINKING (conservative)');
  console.log('════════════════════════════════════════════════════\n');

  // Initial cooldown to ensure any rate limit window resets
  console.log('Waiting 10s for rate limit cooldown...');
  await sleep(10000);

  const configs = [
    { dbType: 'manga' as const, jikanType: 'manga' as const },
    { dbType: 'tv'    as const, jikanType: 'anime' as const },
  ];

  let totalLinked = 0, newFranchises = 0, apiCalls = 0;

  for (const { dbType, jikanType } of configs) {
    const allItems = await prisma.item.findMany({
      where: { type: dbType, malId: { not: null }, isUpcoming: false },
      select: { id: true, title: true, malId: true, franchiseItems: { select: { franchiseId: true } } },
    });
    const byMalId = new Map(allItems.map(i => [i.malId!, i]));
    const unlinked = allItems.filter(i => i.franchiseItems.length === 0);

    console.log(`\n─── ${dbType}: ${unlinked.length} unlinked items to process ───`);

    const resolvedGroups = new Map<number, number>();

    for (let idx = 0; idx < unlinked.length; idx++) {
      const item = unlinked[idx];

      if (resolvedGroups.has(item.malId!)) {
        const fid = resolvedGroups.get(item.malId!)!;
        try {
          await prisma.franchiseItem.create({ data: { franchiseId: fid, itemId: item.id, addedBy: 'wikidata' } });
          totalLinked++;
        } catch { /* already linked */ }
        continue;
      }

      await sleep(DELAY_MS);
      const data = await jikanGet(`/${jikanType}/${item.malId}/relations`);
      apiCalls++;

      if (!data?.data) continue;

      const relatedMalIds: number[] = [item.malId!];
      for (const rel of data.data) {
        if (!LINK_RELATION_TYPES.has(rel.relation)) continue;
        for (const entry of rel.entry || []) {
          if (entry.type === jikanType && entry.mal_id) relatedMalIds.push(entry.mal_id);
        }
      }

      const matches = relatedMalIds.map(id => byMalId.get(id)).filter(Boolean) as any[];
      if (matches.length < 2) continue;

      let franchiseId: number | null = null;
      for (const m of matches) {
        if (m.franchiseItems.length > 0) { franchiseId = m.franchiseItems[0].franchiseId; break; }
      }

      if (!franchiseId) {
        const baseName = item.title
          .replace(/\s+Season\s+\d+.*$/i, '')
          .replace(/\s+Part\s+\d+.*$/i, '')
          .replace(/\s+\d+$/, '')
          .trim();
        const existing = await prisma.franchise.findFirst({ where: { name: { equals: baseName, mode: 'insensitive' } } });
        if (existing) {
          franchiseId = existing.id;
        } else {
          const created = await prisma.franchise.create({
            data: { name: baseName, autoGenerated: true, confidenceTier: 1, description: '', icon: '', cover: '' },
          });
          franchiseId = created.id;
          newFranchises++;
        }
      }

      for (const m of matches) {
        resolvedGroups.set(m.malId!, franchiseId);
        if (m.franchiseItems.length === 0) {
          try {
            await prisma.franchiseItem.create({ data: { franchiseId, itemId: m.id, addedBy: 'wikidata' } });
            totalLinked++;
          } catch { /* dup */ }
        }
      }

      if (idx % 50 === 0) {
        console.log(`  ${idx}/${unlinked.length} processed | ${totalLinked} linked | ${apiCalls} API calls`);
      }
    }
  }

  console.log('\n════════════════════════════════════════════════════');
  console.log('JIKAN v2 COMPLETE');
  console.log('════════════════════════════════════════════════════');
  console.log(`  API calls: ${apiCalls} | New links: ${totalLinked} | New franchises: ${newFranchises}`);

  const [total, unlinked] = await Promise.all([
    prisma.item.count({ where: { isUpcoming: false } }),
    prisma.item.count({ where: { franchiseItems: { none: {} }, isUpcoming: false } }),
  ]);
  console.log(`\n  Items with franchise: ${total - unlinked}/${total} (${(((total-unlinked)/total)*100).toFixed(1)}%)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
