"use client";

import { useState, useEffect } from "react";

interface FranchiseItemData {
  item: { id: number; title: string; type: string; year: number; cover: string };
  addedBy: string;
}

interface FranchiseData {
  id: number;
  name: string;
  icon: string;
  description: string;
  autoGenerated: boolean;
  confidenceTier: number;
  items: FranchiseItemData[];
}

interface SuggestionData {
  id: number;
  itemId1: number;
  itemId2: number;
  reason: string;
  confidenceTier: number;
  item1: { id: number; title: string; type: string; year: number; cover: string } | null;
  item2: { id: number; title: string; type: string; year: number; cover: string } | null;
}

interface SearchItem {
  id: number;
  title: string;
  type: string;
  year: number;
}

const TIER_LABELS: Record<number, { label: string; color: string }> = {
  0: { label: "Manual", color: "#9B5DE5" },
  1: { label: "Tier 1 — High", color: "#2EC4B6" },
  2: { label: "Tier 2 — Medium", color: "#F9A620" },
  3: { label: "Tier 3 — Approved", color: "#3185FC" },
};

const TYPE_COLORS: Record<string, string> = {
  movie: "#E84855", tv: "#C45BAA", book: "#3185FC", manga: "#FF6B6B",
  comic: "#F9A620", game: "#2EC4B6", music: "#9B5DE5", podcast: "#00BBF9",
};

export default function AdminFranchisesPage() {
  const [franchises, setFranchises] = useState<FranchiseData[]>([]);
  const [suggestions, setSuggestions] = useState<SuggestionData[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<"franchises" | "suggestions" | "create">("franchises");

  // Create form state
  const [newName, setNewName] = useState("");
  const [newIcon, setNewIcon] = useState("🔗");
  const [newDesc, setNewDesc] = useState("");
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<SearchItem[]>([]);
  const [selectedItems, setSelectedItems] = useState<SearchItem[]>([]);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  async function loadData() {
    setLoading(true);
    try {
      const [fRes, sRes] = await Promise.all([
        fetch("/api/admin/franchises"),
        fetch("/api/admin/suggestions"),
      ]);
      setFranchises(await fRes.json());
      setSuggestions(await sRes.json());
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  }

  async function deleteFranchise(id: number) {
    if (!confirm("Delete this franchise?")) return;
    await fetch(`/api/admin/franchises?id=${id}`, { method: "DELETE" });
    loadData();
  }

  async function handleSuggestion(id: number, action: "approve" | "reject") {
    await fetch("/api/admin/suggestions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, action }),
    });
    loadData();
  }

  async function searchItems() {
    if (!searchQuery.trim()) return;
    try {
      const res = await fetch(`/api/catalog?limit=20`);
      const items = await res.json();
      const filtered = (items as SearchItem[]).filter((i) =>
        i.title.toLowerCase().includes(searchQuery.toLowerCase())
      );
      setSearchResults(filtered);
    } catch (e) {
      console.error(e);
    }
  }

  async function createFranchise() {
    if (!newName || selectedItems.length < 2) return;
    setCreating(true);
    try {
      await fetch("/api/admin/franchises", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: newName,
          icon: newIcon,
          description: newDesc,
          itemIds: selectedItems.map((i) => i.id),
        }),
      });
      setNewName("");
      setNewIcon("🔗");
      setNewDesc("");
      setSelectedItems([]);
      setSearchResults([]);
      setSearchQuery("");
      loadData();
      setTab("franchises");
    } catch (e) {
      console.error(e);
    }
    setCreating(false);
  }

  const tabs = [
    { id: "franchises" as const, label: `Franchises (${franchises.length})` },
    { id: "suggestions" as const, label: `Suggestions (${suggestions.length})` },
    { id: "create" as const, label: "+ Create" },
  ];

  return (
    <div style={{ maxWidth: 900, margin: "0 auto", padding: "40px 20px" }}>
      <h1 style={{
        fontFamily: "var(--font-serif)", fontSize: 28, fontWeight: 900,
        color: "#fff", marginBottom: 8,
      }}>
        Franchise Admin
      </h1>
      <p style={{ fontSize: 13, color: "var(--text-faint)", marginBottom: 28 }}>
        Manage auto-detected and manual franchise connections
      </p>

      {/* Tabs */}
      <div style={{ display: "flex", gap: 8, marginBottom: 28 }}>
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            style={{
              padding: "8px 16px", borderRadius: 10, fontSize: 12, fontWeight: 600,
              cursor: "pointer", transition: "all 0.15s",
              background: tab === t.id ? "rgba(255,255,255,0.12)" : "rgba(255,255,255,0.04)",
              color: tab === t.id ? "#fff" : "rgba(255,255,255,0.4)",
              border: tab === t.id ? "1px solid rgba(255,255,255,0.18)" : "1px solid rgba(255,255,255,0.06)",
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      {loading && <div style={{ color: "var(--text-faint)", fontSize: 13 }}>Loading...</div>}

      {/* ── Franchises Tab ─────────────────────────────────────────────── */}
      {!loading && tab === "franchises" && (
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          {franchises.length === 0 && (
            <div style={{ color: "var(--text-faint)", fontSize: 13, textAlign: "center", padding: 40 }}>
              No franchises detected yet. Run the detection script first.
            </div>
          )}
          {franchises.map((f) => {
            const tier = TIER_LABELS[f.confidenceTier] || TIER_LABELS[1];
            return (
              <div key={f.id} style={{
                background: "var(--surface-1)", border: "1px solid var(--border)",
                borderRadius: 14, padding: 18, position: "relative",
              }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 }}>
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                      <span style={{ fontSize: 20 }}>{f.icon}</span>
                      <span style={{ fontFamily: "var(--font-serif)", fontSize: 18, fontWeight: 800, color: "#fff" }}>
                        {f.name}
                      </span>
                      <span style={{
                        fontSize: 9, fontWeight: 600, padding: "2px 8px", borderRadius: 6,
                        background: tier.color + "22", color: tier.color, textTransform: "uppercase",
                      }}>
                        {tier.label}
                      </span>
                      {f.autoGenerated && (
                        <span style={{
                          fontSize: 9, padding: "2px 6px", borderRadius: 4,
                          background: "rgba(255,255,255,0.06)", color: "var(--text-faint)",
                        }}>
                          Auto
                        </span>
                      )}
                    </div>
                    {f.description && (
                      <div style={{ fontSize: 11, color: "var(--text-faint)", maxWidth: 500 }}>
                        {f.description}
                      </div>
                    )}
                  </div>
                  <button
                    onClick={() => deleteFranchise(f.id)}
                    style={{
                      background: "rgba(232,72,85,0.1)", border: "1px solid rgba(232,72,85,0.2)",
                      borderRadius: 6, padding: "4px 10px", color: "#E84855", fontSize: 10,
                      cursor: "pointer", fontWeight: 600,
                    }}
                  >
                    Delete
                  </button>
                </div>

                {/* Items */}
                <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
                  {f.items.map((fi) => (
                    <div key={fi.item.id} style={{
                      display: "flex", alignItems: "center", gap: 8,
                      padding: "6px 10px", borderRadius: 8,
                      background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.06)",
                    }}>
                      {fi.item.cover?.startsWith("http") && (
                        <img src={fi.item.cover} alt="" style={{ width: 24, height: 36, objectFit: "cover", borderRadius: 4 }} />
                      )}
                      <div>
                        <div style={{ fontSize: 11, fontWeight: 600, color: "#fff" }}>{fi.item.title}</div>
                        <div style={{
                          fontSize: 9, color: TYPE_COLORS[fi.item.type] || "#888",
                          fontWeight: 600, textTransform: "uppercase",
                        }}>
                          {fi.item.type} · {fi.item.year}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ── Suggestions Tab ────────────────────────────────────────────── */}
      {!loading && tab === "suggestions" && (
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {suggestions.length === 0 && (
            <div style={{ color: "var(--text-faint)", fontSize: 13, textAlign: "center", padding: 40 }}>
              No pending suggestions.
            </div>
          )}
          {suggestions.map((s) => (
            <div key={s.id} style={{
              background: "var(--surface-1)", border: "1px solid var(--border)",
              borderRadius: 12, padding: 16,
            }}>
              <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 10, lineHeight: 1.5 }}>
                {s.reason}
              </div>

              <div style={{ display: "flex", gap: 12, alignItems: "center", marginBottom: 12 }}>
                {s.item1 && (
                  <div style={{
                    display: "flex", alignItems: "center", gap: 6, padding: "4px 8px",
                    borderRadius: 6, background: "rgba(255,255,255,0.04)",
                  }}>
                    <span style={{ fontSize: 9, color: TYPE_COLORS[s.item1.type], fontWeight: 600 }}>
                      {s.item1.type.toUpperCase()}
                    </span>
                    <span style={{ fontSize: 11, color: "#fff" }}>{s.item1.title}</span>
                    <span style={{ fontSize: 9, color: "var(--text-faint)" }}>{s.item1.year}</span>
                  </div>
                )}
                {s.itemId1 !== s.itemId2 && (
                  <>
                    <span style={{ color: "var(--text-faint)", fontSize: 12 }}>↔</span>
                    {s.item2 && (
                      <div style={{
                        display: "flex", alignItems: "center", gap: 6, padding: "4px 8px",
                        borderRadius: 6, background: "rgba(255,255,255,0.04)",
                      }}>
                        <span style={{ fontSize: 9, color: TYPE_COLORS[s.item2.type], fontWeight: 600 }}>
                          {s.item2.type.toUpperCase()}
                        </span>
                        <span style={{ fontSize: 11, color: "#fff" }}>{s.item2.title}</span>
                        <span style={{ fontSize: 9, color: "var(--text-faint)" }}>{s.item2.year}</span>
                      </div>
                    )}
                  </>
                )}
              </div>

              <div style={{ display: "flex", gap: 8 }}>
                {s.itemId1 !== s.itemId2 && (
                  <button
                    onClick={() => handleSuggestion(s.id, "approve")}
                    style={{
                      background: "rgba(46,196,182,0.12)", border: "1px solid rgba(46,196,182,0.25)",
                      borderRadius: 6, padding: "5px 14px", color: "#2EC4B6", fontSize: 11,
                      cursor: "pointer", fontWeight: 600,
                    }}
                  >
                    Approve & Link
                  </button>
                )}
                <button
                  onClick={() => handleSuggestion(s.id, "reject")}
                  style={{
                    background: "rgba(232,72,85,0.08)", border: "1px solid rgba(232,72,85,0.15)",
                    borderRadius: 6, padding: "5px 14px", color: "#E84855", fontSize: 11,
                    cursor: "pointer", fontWeight: 600,
                  }}
                >
                  Dismiss
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ── Create Tab ─────────────────────────────────────────────────── */}
      {!loading && tab === "create" && (
        <div style={{
          background: "var(--surface-1)", border: "1px solid var(--border)",
          borderRadius: 14, padding: 24,
        }}>
          <h3 style={{ fontFamily: "var(--font-serif)", fontSize: 16, fontWeight: 700, color: "#fff", marginBottom: 20 }}>
            Create Franchise
          </h3>

          {/* Name */}
          <div style={{ marginBottom: 16 }}>
            <label style={{ fontSize: 11, color: "var(--text-faint)", display: "block", marginBottom: 6 }}>Name</label>
            <input
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              placeholder="e.g. Dune"
              style={{
                width: "100%", padding: "10px 14px", borderRadius: 8, fontSize: 13,
                background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)",
                color: "#fff", outline: "none", boxSizing: "border-box",
              }}
            />
          </div>

          {/* Icon + Description row */}
          <div style={{ display: "grid", gridTemplateColumns: "80px 1fr", gap: 12, marginBottom: 16 }}>
            <div>
              <label style={{ fontSize: 11, color: "var(--text-faint)", display: "block", marginBottom: 6 }}>Icon</label>
              <input
                value={newIcon}
                onChange={(e) => setNewIcon(e.target.value)}
                style={{
                  width: "100%", padding: "10px 14px", borderRadius: 8, fontSize: 18,
                  background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)",
                  color: "#fff", outline: "none", boxSizing: "border-box", textAlign: "center",
                }}
              />
            </div>
            <div>
              <label style={{ fontSize: 11, color: "var(--text-faint)", display: "block", marginBottom: 6 }}>Description</label>
              <input
                value={newDesc}
                onChange={(e) => setNewDesc(e.target.value)}
                placeholder="Optional description"
                style={{
                  width: "100%", padding: "10px 14px", borderRadius: 8, fontSize: 13,
                  background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)",
                  color: "#fff", outline: "none", boxSizing: "border-box",
                }}
              />
            </div>
          </div>

          {/* Item search */}
          <div style={{ marginBottom: 16 }}>
            <label style={{ fontSize: 11, color: "var(--text-faint)", display: "block", marginBottom: 6 }}>
              Add items (search by title)
            </label>
            <div style={{ display: "flex", gap: 8 }}>
              <input
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && searchItems()}
                placeholder="Search..."
                style={{
                  flex: 1, padding: "10px 14px", borderRadius: 8, fontSize: 13,
                  background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)",
                  color: "#fff", outline: "none",
                }}
              />
              <button
                onClick={searchItems}
                style={{
                  padding: "10px 16px", borderRadius: 8, fontSize: 12, fontWeight: 600,
                  background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.12)",
                  color: "#fff", cursor: "pointer",
                }}
              >
                Search
              </button>
            </div>
          </div>

          {/* Search results */}
          {searchResults.length > 0 && (
            <div style={{ marginBottom: 16, maxHeight: 200, overflowY: "auto" }}>
              {searchResults.map((item) => {
                const selected = selectedItems.some((si) => si.id === item.id);
                return (
                  <button
                    key={item.id}
                    onClick={() => {
                      if (selected) {
                        setSelectedItems(selectedItems.filter((si) => si.id !== item.id));
                      } else {
                        setSelectedItems([...selectedItems, item]);
                      }
                    }}
                    style={{
                      display: "flex", alignItems: "center", gap: 8, width: "100%",
                      padding: "8px 12px", marginBottom: 4, borderRadius: 6, cursor: "pointer",
                      background: selected ? "rgba(46,196,182,0.12)" : "rgba(255,255,255,0.02)",
                      border: selected ? "1px solid rgba(46,196,182,0.25)" : "1px solid rgba(255,255,255,0.04)",
                      textAlign: "left",
                    }}
                  >
                    <span style={{ fontSize: 9, color: TYPE_COLORS[item.type], fontWeight: 600 }}>
                      {item.type.toUpperCase()}
                    </span>
                    <span style={{ fontSize: 12, color: "#fff", flex: 1 }}>{item.title}</span>
                    <span style={{ fontSize: 10, color: "var(--text-faint)" }}>{item.year}</span>
                    {selected && <span style={{ fontSize: 12, color: "#2EC4B6" }}>✓</span>}
                  </button>
                );
              })}
            </div>
          )}

          {/* Selected items */}
          {selectedItems.length > 0 && (
            <div style={{ marginBottom: 16 }}>
              <label style={{ fontSize: 11, color: "var(--text-faint)", display: "block", marginBottom: 6 }}>
                Selected ({selectedItems.length})
              </label>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {selectedItems.map((item) => (
                  <div key={item.id} style={{
                    display: "flex", alignItems: "center", gap: 6,
                    padding: "4px 10px", borderRadius: 8,
                    background: "rgba(46,196,182,0.08)", border: "1px solid rgba(46,196,182,0.15)",
                  }}>
                    <span style={{ fontSize: 9, color: TYPE_COLORS[item.type], fontWeight: 600 }}>
                      {item.type.toUpperCase()}
                    </span>
                    <span style={{ fontSize: 11, color: "#fff" }}>{item.title}</span>
                    <button
                      onClick={() => setSelectedItems(selectedItems.filter((si) => si.id !== item.id))}
                      style={{
                        background: "none", border: "none", color: "rgba(255,255,255,0.3)",
                        cursor: "pointer", fontSize: 10, padding: "0 2px",
                      }}
                    >
                      ✕
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          <button
            onClick={createFranchise}
            disabled={!newName || selectedItems.length < 2 || creating}
            style={{
              padding: "10px 24px", borderRadius: 10, fontSize: 13, fontWeight: 700,
              background: newName && selectedItems.length >= 2 ? "#E84855" : "rgba(255,255,255,0.06)",
              border: "none", color: "#fff", cursor: newName && selectedItems.length >= 2 ? "pointer" : "default",
              opacity: newName && selectedItems.length >= 2 ? 1 : 0.4,
            }}
          >
            {creating ? "Creating..." : "Create Franchise"}
          </button>
        </div>
      )}
    </div>
  );
}
